### ISSUE TITLE
Each interface of bond is reported as neighbor

### ISSUE THREAD

**Issue by ArpStorm1** [lldpd/lldpd#421]
# Bug description
Running lldpcli on a server with RedHat 7.8 and 4 interfaces connected together as bond, each port of the bond will show 
the neighbors of the other interfaces on the bond. It becomes impossible to identify which port on the switch is the neighbor of the interface.
For example, I have a bond with 4 interfaces: eth0 to eth3, which are connected to 4 ports on switch, Eth0 to Eth3.
Running lldpcli show neigh, eth0 is reporting Eth0 to Eth3 as his neighbors, even though it is connected only to one of them.
## Steps to reproduce the problem

1. Bit lazy, install lldpd version 1.0.1 from yum epel repo.
2. Run lldpcli show neighbors on a server with 4 interfaces which are connected together as bond
 
## Expected outcome

4 results, one from each interface, showing which interface on server is connected to which port on the switch.

## Current outcome

16 results, because each interface is reporting on his neighbor and the other interfaces on the bond as his neighbors,

```

# Additional information

 - lldpcli version 1.0.1

**Comment by vincentbernat** [comment]
Could you provide the output of `ethtool -i bond0` (or the device name you use for the bond), as well as the output of `uname -a`?

**Comment by ArpStorm1** [comment]
ethtool -i bond0 output:
driver: bonding
version: 3.7.1
firmware-version: 2
expansion-rom-version:
bus-info:
supports-statistics: no
supports-tests: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no

uname -a output:
Linux <server_name> 3.10.0-1127.13.1.el7.x86_64 #1 SMP Fri Jun 12 14:34:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vincentbernat** [comment]
Could you run `tcpdump -pni eth0 -ether host 01:80:c2:00:00:0e` for a minute and provide the result?

**Comment by ArpStorm1** [comment]
Hey, Sorry for the delay.

The output is going like that:

<Date> LLDP, length <length>: <Switch hostname>
<Date> LLDP, length <length>: <Server_name>

And that messages are repeating themselves every 30 seconds

**Comment by vincentbernat** [comment]
I don't see how this could happen. Could you provide a complete output of `lldpctl`?

**Comment by ArpStorm1** [comment]
Hi, this environment is a disconnected environment, so I can't provide the exact values.
Although, the output is going like that:

------
LLDP neighbors:
-----
Interface: ens1f0, via: LLDP, RID: 1, Time: X days, [Time]
  Chassis:
    ChassisID: mac [mac]
    SysName: [Leaf1-name]
    SysDescr: Cisco Nexus Operating System(NX-OS) Software 9.2(3)
    MgmtIP: [Leaf_IP]
    Capability: Bridge, on
    Capability: Router, on
 Port:
    PortID: [Port **X** in Leaf]
    PortDescr: [Description of the port in the leaf]
    TTL: 120
    Vlan: [vlan_number] pvid: yes
 Unknown TLVs:
     TLV: [Some_TLV]

Right after would come:

Interface: ens1f0, via: LLDP, RID: 1, Time: X days, [Time]
  Chassis:
    ChassisID: mac [mac]
    SysName: [Leaf1-name]
    SysDescr: Cisco Nexus Operating System(NX-OS) Software 9.2(3)
    MgmtIP: [Leaf_IP]
    Capability: Bridge, on
    Capability: Router, on
 Port:
    PortID: [Port **Y** in Leaf]
    PortDescr: [Description of the port in the leaf]
    TTL: 120
    Vlan: [vlan_number] pvid: yes
 Unknown TLVs:
     TLV: [Some_TLV]

And so on for all the interfaces...
For example - if ens1f0(Connected to port X in the switch) is bonded with ens1f1(Connected to port Y in the switch), each one of them would report like they both connected to port X and to port Y.

**Comment by vincentbernat** [comment]
Maybe you can spot something "fishy" when running `lldpd -dddd`?

**Comment by ArpStorm1** [comment]
Umm.. Acutally there is something fishy...

[ DBG/main] lldpd 1.0.1 starting...
[ DBG/main] creating control socket
[ DBG/control] create control socket /run/lldpd/lldpd.socket
[INFO/main] unable to create control socket because it already exists
[INFO/main] check if another instance is running
[ DBG/control] connect to control socket /run/lldpd/lldpd.socket
[WARN/main] another instance is running, please stop it
[CRIT/main] giving up

**Comment by vincentbernat** [comment]
You need to stop the running one first.

**Comment by vincentbernat** [comment]
What's the output of `ip -d l l dev bond0`?

**Comment by ArpStorm1** [comment]
@vincentbernat  How to stop the first one? I'm just running the daemon using service lldpd start...
The output is:
bond0: <BROADCAST, MULTICAST, MASTER, UP, LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000 link/ether [mac_address] brd [mac_address_broadcast] promiscuity 0
bond mode 802.3ad miimon 100 updelay 0 downdelay 0 use_carrier 1 arp_interval 0 arp_validate none arp_all_targets any primary_reselect always fail_over_mac none xmit_hash_policy layer3+4 resend_igmp 1 num_grat_arp 1 all_slaves_active 0 min_links 0 lp_interval 1 packets_per_slave 1 lacp_rate fast ad_select stable ad_aggregator 4 ad_num_ports 4 ad_factor_key 15 ad_partner_key 32864 ad_partner_mac [mac_address] ad_actor_sys_prio 65535 ad_user_port_key 0 ad_actor_system 00:00:00:00:00:00 tlb_dynamic_lb 1 addrgenmode eui64 numtxqueues 16 numrxqueues 16 gso_max_size 65536 gso_max_segs 65535

**Comment by vincentbernat** [comment]
With `service lldpd stop`. `lldpd -dddd` will run a new instance while logging a lot of stuff. Only one instance of lldpd can run at the same time.

**Comment by ArpStorm1** [comment]
Did `service lldpd stop` and then tried to rerun `lldpd -dddd`.
Got the same result as before(Reminder):
`[ DBG/main] lldpd 1.0.1 starting...
[ DBG/main] creating control socket
[ DBG/control] create control socket /run/lldpd/lldpd.socket
[INFO/main] unable to create control socket because it already exists
[INFO/main] check if another instance is running
[ DBG/control] connect to control socket /run/lldpd/lldpd.socket
[WARN/main] another instance is running, please stop it
[CRIT/main] giving up`

Also I made sure that the service is not running using `service lldpd status`

**Comment by vincentbernat** [comment]
Can you check with `ps auxww | grep lldpd` that nothing else is running?

**Comment by ArpStorm1** [comment]
OK... Looks like really there was something there even though I've used `service lldpd stop`... I've killed the process and then I could run lldpd -ddd.
Output:
[INFO/main] protocol LLDP enabled
[INFO/main] protocol CDPv1 disabled
[INFO/main] protocol CDPv2 disabled
[INFO/main] protocol SONMP disabled
[INFO/main] protocol EDP disabled
[INFO/main] protocol FDP disabled
[INFO/event] libevent 2.0.21-stable initalized with epoll method
[WARN/interfaces] cannot get ethtool link information with GLINKSETTINGS (requires 4.9+): Operation not permitted
[INFO/lldpctl] lldpd should resume operations

**Comment by vincentbernat** [comment]
It's four `d`, `-dddd`.

**Comment by ArpStorm1** [comment]
Hi, it was solved by upgrading the version. Thanks!
