### ISSUE TITLE
Feature request [linux]: enable router capability when IPv6 forwarding is enabled on at least one interface

### ISSUE THREAD

**Issue by ordex** [lldpd/lldpd#425]
Right now, on Linux, the Router capability is enabled only when /proc/sys/net/ipv4/ip_forward is set to 1.
This proc file, as the name dictates, reflects only the forwarding status of the IPv4 stack.

A host that is actually acting as IPv6 only router will not be advertised with the Router capability in lldpd.

It would be nice if lldpd could check the value set in all the files matching the expression /proc/sys/net/ipv6/conf/<iface>/forwarding (excluding iface="all" and iface="default") and activate the Router capability if at least one file contains 1.

The implementation should be logically easy, but requires adding a new priv i/o command to allow the unprivileged process to open the /proc/sys/net/ipv6/conf directory and list its children.

**Comment by vincentbernat** [comment]
For IPv6, forwarding is enabled if `all` is set. Per-iface values only defines if an interface should act like a router (NA, RA). So, it seems easy to test. Do you want to implement that?

**Comment by ordex** [comment]
Interesting, I just found that out during my tests.
I thought enabling forwarding only on selected interface would work too.
Then this features becomes quite easy to implement  :)

Sure, I'll take a stab at it.

**Comment by ordex** [comment]
PR #426 created
