### ISSUE TITLE
lldp cross compiling for armv7l issue

### ISSUE THREAD

**Issue by Maku-chan** [lldpd/lldpd#428]
Hello,

I am trying to install the lldp 1.0.7 version. I performed the below mentioned steps:

1)
```
../configure --host=arm-linux --build=x86_64-linux --target=arm CC=/usr/bin/arm-linux-gnueabihf-gcc

output:
------------------ Summary ------------------
 lldpd version 1.0.3
  OS.............: Linux
  Prefix.........: /usr/local
  C Compiler.....: /usr/bin/arm-linux-gnueabihf-gcc  -fdiagnostics-show-option -fdiagnostics-color=auto -pipe -Wall -W -Wextra -Wformat -Wformat-security -Wfatal-errors -Wcast-align -Winline -Wpointer-arith -fno-omit-frame-pointer -Wno-unused-parameter -Wno-missing-field-initializers -Wno-sign-compare -fstack-protector -fstack-protector-all -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -g -O2 
  Linker.........: /usr/arm-linux-gnueabihf/bin/ld  -Wl,-z,relro -Wl,-z,now   
  Libevent.......: embedded
  Readline.......: no

 Optional features:
  SNMP support...: no
  CDP............: yes
  FDP............: yes
  EDP............: yes
  SONMP..........: yes
  LLDPMED........: yes
  DOT1...........: yes
  DOT3...........: yes
  CUSTOM.........: yes
  XML output.....: yes
  Oldies support.: no
  seccomp........: no
  libbsd.........: no

 Privilege separation:
  Enabled........: yes
  User/group.....: _lldpd/_lldpd
  Chroot.........: /usr/local/var/run/lldpd

 Instrumentation (for devs only):
  Sanitizers.....: none
  Coverage.......: no
------------- Compiler version --------------
arm-linux-gnueabihf-gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-------------- Linker version ---------------
GNU ld (GNU Binutils for Ubuntu) 2.34
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
---------------------------------------------

Check the above options and compile with:
 make
```
2) Then execute the make command
```
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lxml2
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:581: lldpcli] Error 1
make[2]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.3/build/src/client'
make[1]: *** [Makefile:619: all-recursive] Error 1
make[1]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.3/build'
```
I am getting this error even though i haven't give the flag (--with-xml)

How can i resolve this issue.

Thanks.

**Comment by vincentbernat** [comment]
Can you attach the `config.log` file? You can workaround the bug with `--without-xml`.

**Comment by Maku-chan** [comment]
I executed the command with --without-xml

1) ../configure --host=armv7l-unknown-linux-gnueabihf --with-privsep-user=root --with-privsep-group=root CC=/usr/bin/arm-linux-gnueabihf-gcc --prefix=/home/maku-chan/build_lldp --without-xml

Output:
------------------ Summary ------------------
 lldpd version 1.0.7
  OS.............: Linux
  Prefix.........: /home/maku-chan/build_lldp
  C Compiler.....: /usr/bin/arm-linux-gnueabihf-gcc  -fdiagnostics-show-option -fdiagnostics-color=auto -pipe -Wall -W -Wextra -Wformat -Wformat-security -Wimplicit-fallthrough -Wfatal-errors -Winline -Wpointer-arith -fno-omit-frame-pointer -Wno-cast-align -Wno-unused-parameter -Wno-missing-field-initializers -Wno-sign-compare -fstack-protector -fstack-protector-all -fstack-protector-strong -fstack-clash-protection  -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -g -O2 
  Linker.........: /usr/arm-linux-gnueabihf/bin/ld  -Wl,-z,relro -Wl,-z,now   
  Libevent.......: embedded
  Readline.......: no

 Optional features:
  SNMP support...: no
  CDP............: yes
  FDP............: yes
  EDP............: yes
  SONMP..........: yes
  LLDPMED........: yes
  DOT1...........: yes
  DOT3...........: yes
  CUSTOM.........: yes
  XML output.....: no
  Oldies support.: no
  seccomp........: no
  libbsd.........: no

 Privilege separation:
  Enabled........: yes
  User/group.....: root/root
  Chroot.........: /home/maku-chan/build_lldp/var/run/lldpd

 Instrumentation (for devs only):
  Sanitizers.....: none
  Coverage.......: no
------------- Compiler version --------------
arm-linux-gnueabihf-gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-------------- Linker version ---------------
GNU ld (GNU Binutils for Ubuntu) 2.34
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
---------------------------------------------

Check the above options and compile with:
 make

2) then run make

output:
make[2]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/src/client'
Making all in tests
make[2]: Entering directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/tests'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/tests'
Making all in osx
make[2]: Entering directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/osx'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/osx'
make[2]: Entering directory '/home/maku-chan/Downloads/lldpd-1.0.7/build'
  GEN      ChangeLog
make[2]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.7/build'
make[1]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.7/build'

3) make install

Output:
libtool: warning: remember to run 'libtool --finish /home/maku-chan/build_lldp/lib'
 /usr/bin/mkdir -p '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/include'
 /usr/bin/install -c -m 644 ../../../src/lib/lldpctl.h '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/include'
 /usr/bin/mkdir -p '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/lib/pkgconfig'
 /usr/bin/install -c -m 644 lldpctl.pc '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/lib/pkgconfig'
make[2]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/src/lib'
make[1]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/src/lib'
Making install in src/client
make[1]: Entering directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/src/client'
make[2]: Entering directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/src/client'
cd /home/maku-chan/build_lldp/home/maku-chan/build_lldp/sbin && rm -f lldpctl
cd /home/maku-chan/build_lldp/home/maku-chan/build_lldp/sbin && ln -s lldpcli lldpctl
 /usr/bin/mkdir -p '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/sbin'
  /bin/bash ../../libtool   --mode=install /usr/bin/install -c lldpcli '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/sbin'
libtool: warning: '../../src/lib/liblldpctl.la' has not been installed in '/home/maku-chan/build_lldp/lib'
libtool: install: /usr/bin/install -c .libs/lldpcli /home/maku-chan/build_lldp/home/maku-chan/build_lldp/sbin/lldpcli
 /usr/bin/mkdir -p '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/share/bash-completion/completions'
 /usr/bin/install -c -m 644 ../../../src/client/completion/lldpcli '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/share/bash-completion/completions'
 /usr/bin/mkdir -p '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/etc/lldpd.d'
 /usr/bin/install -c -m 644 ../../../src/client/README.conf '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/etc/lldpd.d'
 /usr/bin/mkdir -p '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/share/zsh/site-functions'
 /usr/bin/install -c -m 644 ../../../src/client/completion/_lldpcli '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/share/zsh/site-functions'
 /usr/bin/mkdir -p '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/share/man/man8'
 /usr/bin/install -c -m 644 ../../../src/client/lldpctl.8 lldpcli.8 '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/share/man/man8'
make[2]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/src/client'
make[1]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/src/client'
Making install in tests
make[1]: Entering directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/tests'
make[2]: Entering directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/tests'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/tests'
make[1]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/tests'
Making install in osx
make[1]: Entering directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/osx'
make[2]: Entering directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/osx'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/osx'
make[1]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.7/build/osx'
make[1]: Entering directory '/home/maku-chan/Downloads/lldpd-1.0.7/build'
  GEN      ChangeLog
make[2]: Entering directory '/home/maku-chan/Downloads/lldpd-1.0.7/build'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/share/doc/lldpd'
 /usr/bin/install -c -m 644 ../README.md ../NEWS ../CONTRIBUTE.md ../LICENSE '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/share/doc/lldpd'
  GEN      ChangeLog
 /usr/bin/mkdir -p '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/share/doc/lldpd'
 /usr/bin/install -c -m 644 ChangeLog '/home/maku-chan/build_lldp/home/maku-chan/build_lldp/share/doc/lldpd'
make[2]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.7/build'
make[1]: Leaving directory '/home/maku-chan/Downloads/lldpd-1.0.7/build'


It seems to be cross compiled. But the issue is that when I run the compiled version in the other board I get the below mentioned error. 
cd /home/maku-chan/build_lldp/sbin
./lldpd: /lib/libc.so.6: version `GLIBC_2.28' not found (required by ./lldpd)

so does GCC required to run this service even after cross compiling.

Thanks

**Comment by vincentbernat** [comment]
Is your target system running Ubuntu 20.04?

**Comment by Maku-chan** [comment]
yes it is running 20.04

**Comment by Maku-chan** [comment]
I am building on 20.04 and i am cross compiling for armv7l

**Comment by Maku-chan** [comment]
# /lib/libc.so.6
GNU C Library (GNU libc) stable release version 2.25, by Roland McGrath et al.
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 7.3.1 20180425 [linaro-7.3-2018.05 revision d29120a424ecfbc167ef90065c0eeb7f91977701].
Available extensions:
	crypt add-on version 2.1 by Michael Glad and others
	GNU Libidn by Simon Josefsson
	Native POSIX Threads Library by Ulrich Drepper et al
	BIND-8.2.3-T5B
libc ABIs: UNIQUE
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.

The version on the other board is 2.25. Is it possible to cross compile for this version.

**Comment by vincentbernat** [comment]
You need to build the whole toolchain for your target. The cross-compiler shipped with Ubuntu is to cross-compile for Ubuntu targets.

**Comment by Maku-chan** [comment]
How can I do that. As I usually cross compile other files through the same procedure and they work fine.

**Comment by Maku-chan** [comment]
so i want to cross compile for armv7l on my x86_64 system so the target will be armv7l and host will be x86_64 right?

**Comment by vincentbernat** [comment]
The `README.md` contains an example on how to crosscompile with the Android toolchain. This should be similar, but you need to build the toolchain matching your target (or download the one provided by the vendor if any).

**Comment by Maku-chan** [comment]
Hi,

Thanks a lot. Through the proper toolchain i was able to cross compile but now i am getting the below error when I run the lldpd service in the other board.

# ./lldpd -ddd
1970-01-01T00:18:47 [WARN/main] unable to create control socket at /home/maku-chan/build_lldp/var/run/lldpd.socket: No such file or directory
1970-01-01T00:18:47 [CRIT/main] giving up

**Comment by Maku-chan** [comment]
Hi, 

I fixed that error but now I am getting the below error.

# ./lldpd -ddd -L ./lldpcli
1970-01-01T00:24:07 [INFO/privsep] no libcap support, running monitor as root
1970-01-01T00:24:07 [INFO/main] protocol LLDP enabled
1970-01-01T00:24:07 [INFO/main] protocol CDPv1 disabled
1970-01-01T00:24:07 [INFO/main] protocol CDPv2 disabled
1970-01-01T00:24:07 [INFO/main] protocol SONMP disabled
1970-01-01T00:24:07 [INFO/main] protocol EDP disabled
1970-01-01T00:24:07 [INFO/main] protocol FDP disabled
1970-01-01T00:24:07 [INFO/event] libevent 2.1.11-stable initialized with epoll method
lldpcli: error while loading shared libraries: liblldpctl.so.4: cannot open shared object file: No such file or directory

**Comment by Maku-chan** [comment]
Hi,

It is working now. The issue was with the searching for the directories.

Thanks.

**Comment by vincentbernat** [comment]
Ok, I am closing the issue then.
