### ISSUE TITLE
Need flag to control whether using interface alias as description / writing to interface alias

### ISSUE THREAD

**Issue by Harry-Chen** [lldpd/lldpd#431]
`lldpd` on Linux will set the alias of an interface (by writing to `/sys/class/net/XXX/ifalias`) that has received has an LLDP neighbour. Also when sending LLDP / CDP / ... messages, `lldpd` will use the alias (which is copied to `p_descr`) prior to the interface name if it existed.
 
These two behaviours make the LLDP / CDP neighbour (for example, named YYY) of a server running `lldpd` receives the port description in the form of `connected to YYY (1/0/1)`, but this provides no information about the interface on the server side (because you know exactly what port it is on YYY).

I suppose adding either (both will be better) flag can solve this:

* control whether to write the interface alias file, or
* control whether to use the alias prior to interface name.

**Comment by vincentbernat** [comment]
❦ 30 janvier 2021 06:32 -08, Shengqi Chen:

> I suppose adding either (both will be better) flag can solve this:
>
> * control whether to write the interface alias file, or
> * control whether to use the alias prior to interface name.

The first is already implemented: configure system interface
description. I suppose we could avoid using the alias for LLDP packets
if this option is set.

**Comment by Harry-Chen** [comment]
@vincentbernat Thanks for the super quick reply & fix!
