### ISSUE TITLE
show configuration per interface

### ISSUE THREAD

**Issue by mgregr** [lldpd/lldpd#432]
Is there a way how to show configuration per interface? If I disable lldp on an interface, is it possible to find out which interface has lldp disabled?

e.g. I run `lldpcli configure ports eth0 lldp status disabled`. Later, I would like to check if the lldp status on the `eth0` interface is disabled or enabled. Something like `lldpcli show configuration ports eth0` or something different. `show configuration` displays only global config. Neither `show interface` nor `show interface detail` show the information. 

lldp version 1.0.1

**Comment by vincentbernat** [comment]
Currently, this is not implemented. This doesn't seem hard to implement
it as this only needs to be done on client side.
