### ISSUE TITLE
memory leak for bad cdp packets

### ISSUE THREAD

**Issue by cq674350529** [lldpd/lldpd#436]
# Bug description

In commit https://github.com/lldpd/lldpd/commit/a8d3c90feca548fc0656d95b5d278713db86ff61, a memory leak issue existing in `lldp_decode()` for lldp packets is fixed. When inverstigating the `cdp_decode()` for cdp packets, it seems that by sending crafted cdp packets, it's also possible to cause memory leak. 

As we can see, as for each `CDP_TLV_CHASSIS`, `calloc()` will be called and the returned value is assigned to `chassis->c_name`. If a cdp packet contains multiple `CDP_TLV_CHASSIS`, then calloc() will be called many times, and only the last returned value will be recorded and freed in the end, thus causing memory leak.

https://github.com/lldpd/lldpd/blob/8c69002b45bbb23764dc9a6a2c2ce8f9275717d4/src/daemon/protocols/cdp.c#L334-L344

https://github.com/lldpd/lldpd/blob/8c69002b45bbb23764dc9a6a2c2ce8f9275717d4/src/daemon/protocols/cdp.c#L441-L455

**Comment by vincentbernat** [comment]
Thanks! There were several other occurrences, including in LLDP. I think I have fixed them all.
