### ISSUE TITLE
/22 subnet setup causes the loss of lldpctl 

### ISSUE THREAD

**Issue by gmangat-st** [lldpd/lldpd#440]
/22 subnet setup causes the loss of lldpctl information for Igb0. After moving servers to new subnet , noticed  lldp neighbor no longer shows up. In order to get it back we have to run tcpdump on the interface but after a reboot the information is lost.

```
[root@kw-server ~]# lldpctl igb0
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
[root@kw-server ~]#
[root@kw-server ~]# uname -r
4.19.82-1300.strike.fc29.x86_64
[root@kw-server ~]# lldpctl igb0
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
[root@kw-server ~]#
[root@kw-server ~]# tcpdump -pni igb0 -vv -X ether host 01:80:c2:00:00:0e
tcpdump: listening on igb0, link-type EN10MB (Ethernet), capture size 262144 bytes
15:55:58.428107 LLDP, length 224
        Chassis ID TLV (1), length 7
          Subtype MAC address (4): 3c:ec:ef:1e:d2:18
          0x0000:  043c ecef 1ed2 18
        Port ID TLV (2), length 5
          Subtype Interface Name (5): igb0
          0x0000:  0569 6762 30
        Time to Live TLV (3), length 2: TTL 120s
          0x0000:  0078
        System Name TLV (5), length 30: kw-server.domain.com
          0x0000:  6b77 2d64 6576 332e 7374 7269 6b65 7465
          0x0010:  6368 6e6f 6c6f 6769 6573 2e63 6f6d
        System Description TLV (6), length 103
          Fedora 29 (Twenty Nine) Linux 4.19.82-1300.strike.fc29.x86_64 #1 SMP Fri Nov 8 10:49:58 EST 2019 x86_64
          0x0000:  4665 646f 7261 2032 3920 2854 7765 6e74
          0x0010:  7920 4e69 6e65 2920 4c69 6e75 7820 342e
          0x0020:  3139 2e38 322d 3133 3030 2e73 7472 696b
          0x0030:  652e 6663 3239 2e78 3836 5f36 3420 2331
          0x0040:  2053 4d50 2046 7269 204e 6f76 2038 2031
          0x0050:  303a 3439 3a35 3820 4553 5420 3230 3139
          0x0060:  2078 3836 5f36 34
        System Capabilities TLV (7), length 4
          System  Capabilities [Bridge, WLAN AP, Router, Station Only] (0x009c)
          Enabled Capabilities [Station Only] (0x0080)
          0x0000:  009c 0080
        Management Address TLV (8), length 12
          Management Address length 5, AFI IPv4 (1): xxx.xx.xx.xx
          Interface Index Interface Numbering (2): 6
          0x0000:  0501 ac1d 2848 0200 0000 0600
        Port Description TLV (4), length 4: igb0
          0x0000:  6967 6230
        Organization specific TLV (127), length 15: OUI Ethernet bridged (0x0080c2)
          VLAN name Subtype (3)
            vlan id (VID): 925
            vlan name: igb0.925
          0x0000:  0080 c203 039d 0869 6762 302e 3932 35
        Organization specific TLV (127), length 9: OUI IEEE 802.3 Private (0x00120f)
          Link aggregation Subtype (3)
            aggregation status [supported], aggregation port ID 0
          0x0000:  0012 0f03 0100 0000 00
        Organization specific TLV (127), length 9: OUI IEEE 802.3 Private (0x00120f)
          MAC/PHY configuration/status Subtype (1)
            autonegotiation [enabled] (0x02)
            PMD autoneg capability [unknown] (0x8000)
            MAU type 1000BASET fdx (0x001e)
          0x0000:  0012 0f01 0280 0000 1e
          0x0000:  0012 0f01 0280 0000 1e
        End TLV (0), length 0
        0x0000:  0207 043c ecef 1ed2 1804 0505 6967 6230  ...<........igb0
        0x0010:  0602 0078 0a1e 6b77 2d64 6576 332e 7374  ...x..kw-server.do
        0x0020:  7269 6b65 7465 6368 6e6f 6c6f 6769 6573  main.com
        0x0030:  2e63 6f6d 0c67 4665 646f 7261 2032 3920  .com.gFedora.29.
        0x0040:  2854 7765 6e74 7920 4e69 6e65 2920 4c69  (Twenty.Nine).Li
        0x0050:  6e75 7820 342e 3139 2e38 322d 3133 3030  nux.4.19.82-1300
        0x0060:  2e73 7472 696b 652e 6663 3239 2e78 3836  .strike.fc29.x86
        0x0070:  5f36 3420 2331 2053 4d50 2046 7269 204e  _64.#1.SMP.Fri.N
        0x0080:  6f76 2038 2031 303a 3439 3a35 3820 4553  ov.8.10:49:58.ES
        0x0090:  5420 3230 3139 2078 3836 5f36 340e 0400  T.2019.x86_64...
        0x00a0:  9c00 8010 0c05 01ac 1d28 4802 0000 0006  .........(H.....
        0x00b0:  0008 0469 6762 30fe 0f00 80c2 0303 9d08  ...igb0.........
        0x00c0:  6967 6230 2e39 3235 fe09 0012 0f03 0100  igb0.925........
        0x00d0:  0000 00fe 0900 120f 0102 8000 001e 0000  ................
^C
1 packet captured
1 packet received by filter
0 packets dropped by kernel
[root@kw-server ~]#
[root@kw-server ~]# lldpctl igb0
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
[root@kw-server ~]#
[root@kw-server ~]# tcpdump -i igb0 -nvv > /dev/null
tcpdump: listening on igb0, link-type EN10MB (Ethernet), capture size 262144 bytes
 ^C1197 packets captured
1199 packets received by filter
0 packets dropped by kernel
5 packets dropped by interface
[root@kw-server ~]# 
[root@kw-server ~]# lldpctl igb0
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
Interface:    igb0, via: LLDP, RID: 2, Time: 0 day, 00:02:16
  Chassis:
    ChassisID:    mac 00:24:14:c9:a2:de
    SysName:      xx-xxxxx-xxxxxx.domain.com
    SysDescr:     Cisco IOS Software, Catalyst 4500 L3 Switch Software (cat4500-ENTSERVICESK9-M), Version 12.2(53)SG, RELEASE SOFTWARE (fc3)
                  Technical Support: http://www.cisco.com/techsupport
                  Copyright (c) 1986-2009 by Cisco Systems, Inc.
                  Compiled Thu 16-Jul-09 19:10 by p
    MgmtIP:       172.20.227.28
    Capability:   Bridge, on
    Capability:   Router, on
  Port:
    PortID:       ifname Gi1/31
    PortDescr:    [xxxxxxxxx][drac]
    TTL:          120
    PMD autoneg:  supported: yes, enabled: yes
      Adv:          10Base-T, HD: yes, FD: no
      Adv:          1000Base-X, HD: no, FD: yes
      Adv:          1000Base-T, HD: yes, FD: no
      MAU oper type: 1000BaseTFD - Four-pair Category 5 UTP, full duplex mode
  VLAN:         926, pvid: yes
-------------------------------------------------------------------------------
[root@kw-server ~]#
```

**Comment by vincentbernat** [comment]
How did you make the configuration change? What's the output of `ip maddr dev igb0`?

**Comment by gmangat-st** [comment]
Hi
[root@ ~]# ip maddr show igb0
2:      igb0
        link  01:00:5e:00:00:01 users 3
        link  01:80:c2:00:00:21 users 3
        link  01:80:c2:00:00:0e users 2 static
        link  01:80:c2:00:00:03 users 2 static
        link  01:80:c2:00:00:00 users 2 static
        link  01:00:0c:cc:cc:cc users 2 static
        inet  224.0.0.1
[root@ ~]#

**Comment by vincentbernat** [comment]
Did you restart lldpd in the meantime?

**Comment by gmangat-st** [comment]
No,  did _not_ restart lldpc

**Comment by vincentbernat** [comment]
The only reason a tcpdump would unblock the situation would be because LLDP MAC address was not present in `ip maddr`. As it is now present, maybe the link flapped and lldpd did register the MAC address again. Does the entry still exists when using lldpctl?

**Comment by gmangat-st** [comment]
Yes, entry still there

***@***.***#ip maddr show igb0
2:      igb0
        link  01:00:5e:00:00:01 users 3
        link  01:80:c2:00:00:21 users 3
        link  01:80:c2:00:00:0e users 2 static
        link  01:80:c2:00:00:03 users 2 static
        link  01:80:c2:00:00:00 users 2 static
        link  01:00:0c:cc:cc:cc users 2 static
        inet  224.0.0.1
***@***.***#lldpctl
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
***@***.***#
***@***.***#tcpdump  -nvv -i igb0 > /dev/null
tcpdump: listening on igb0, link-type EN10MB (Ethernet), capture size 262144 bytes
^C126090 packets captured
126100 packets received by filter
0 packets dropped by kernel
3 packets dropped by interface
***@***.***#lldpctl
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
Interface:    igb0, via: LLDP, RID: 1, Time: 0 day, 00:01:11
  Chassis:
    ChassisID:    mac 00:24:14:c9:a2:de
    SysName:      xxxx
    SysDescr:     Cisco IOS Software, Catalyst 4500 L3 Switch Software (cat4500-ENTSERVICESK9-M), Version 12.2(53)SG, RELEASE
SOFTWARE (fc3)
                  Technical Support: http://www.cisco.com/techsupport
                  Copyright (c) 1986-2009 by Cisco Systems, Inc.
                  Compiled Thu 16-Jul-09 19:10 by p
    MgmtIP:       xxxxxx
    Capability:   Bridge, on
    Capability:   Router, on
  Port:
    PortID:       ifname Gi1/31
    PortDescr:    [xxxxx]
    TTL:          120
    PMD autoneg:  supported: yes, enabled: yes
      Adv:          10Base-T, HD: yes, FD: no
      Adv:          1000Base-X, HD: no, FD: yes
      Adv:          1000Base-T, HD: yes, FD: no
      MAU oper type: 1000BaseTFD - Four-pair Category 5 UTP, full duplex mode
  VLAN:         926, pvid: yes
-------------------------------------------------------------------------------
***@***.***#
***@***.***#ip maddr show igb0
2:      igb0
        link  01:00:5e:00:00:01 users 3
        link  01:80:c2:00:00:21 users 3
        link  01:80:c2:00:00:0e users 2 static
        link  01:80:c2:00:00:03 users 2 static
        link  01:80:c2:00:00:00 users 2 static
        link  01:00:0c:cc:cc:cc users 2 static
        inet  224.0.0.1
***@***.***#

**Comment by vincentbernat** [comment]
Can you run:

```
tcpdump -eni igb0 ether host 01:80:c2:00:00:0e
```

One incoming packet is enough.

Also, once the entry has expired, can you run:

```
tcpdump -epni igb0 ether host 01:80:c2:00:00:0e
```

And check if tcpdump sees any incoming packets.

**Comment by gmangat-st** [comment]
***@***.***#lldpctl
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
***@***.***#tcpdump  -epni igb0 -c 1 host 01:80:c2:00:00:0e
tcpdump: ethernet address used in non-ether expression
***@***.***#
***@***.***#tcpdump  -epni igb0 -c 1 '(ether src  01:80:c2:00:00:0e or ether dst 01:80:c2:00:00:0e)'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on igb0, link-type EN10MB (Ethernet), capture size 262144 bytes
11:00:23.708104 3c:ec:ef:1e:d2:18 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 238: LLDP, length 224: xxxx.domain.com
1 packet captured
1 packet received by filter
0 packets dropped by kernel
***@***.***#

**Comment by vincentbernat** [comment]
Does the packet you capture is an incoming or outgoing packet? I assume this is an outgoing packet. You need to check if you have an incoming packet. Capture more packets to see if you are able to see incoming packets. If you don't see an incoming packet, can you try:

```
ip maddr del 01:80:c2:00:00:0e dev igb0
ip maddr add 01:80:c2:00:00:0e dev igb0
```

If it starts working again, it's a bug somewhere in the kernel.

**Comment by vincentbernat** [comment]
Closing this bug for inactivity. I don't think this is a bug in lldpd.
