### ISSUE TITLE
Support for newer 40g and 100g Intel Ethernet adapters (ice.ko)

### ISSUE THREAD

**Issue by majst01** [lldpd/lldpd#444]
Hi,

i am the author of a golang based very simple special purpose lldpd (https://github.com/metal-stack/go-lldpd) which is used in a bare metal provisioning stack. We got new servers with the new intel 810 based chips with 100GB/s connectivity and our lldpd stopped working, e.g. the switch did not see our packet anymore.

I tried this lldpd for reference, but the same. The only lldpd which is able to still work as expected was lldpad from intel.

After digging around with no luck, i contacted some intel engineers and the solution is to send the ethernet packets to the socket which must have set the socket priority to at least TC_PRIO_CONTROL (7).

If i where able to code in `C` i had opened a pull request for this purpose, but i can't.

Hope this helps.

Greetings

**Comment by vincentbernat** [comment]
Thanks for the notice. I'll implement that! Maybe you also have a trick to easily disable firmware LLDP without poking in `/sys/kernel/debug`?

**Comment by majst01** [comment]
The firmware lldp trick is also required, this is another quirk required for new intel cards.

**Comment by majst01** [comment]
My firmware lldp trick is like:

```
mount -t debugfs none /sys/kernel/debug
echo lldp stop > /sys/kernel/debug/i40e/0000:01:00.2/command
```

implementation is here:
https://github.com/metal-stack/go-lldpd/blob/master/main.go#L116

**Comment by vincentbernat** [comment]
I think I'll try to do the same. Just documenting it is not enough.

**Comment by vincentbernat** [comment]
Fixed by a74fd8ca9c02.

**Comment by boomertsfx** [comment]
Also you can use `ethtool --set-priv-flags ${int} disable-fw-lldp on` to disable the built-in DCB/DCBX LLDP agent.

**Comment by vincentbernat** [comment]
Oh thanks! That's smarter! I'll do that.

**Comment by majst01** [comment]
But @boomertsfx does not work for ice.ko based cards still, see my lenghtly discussion with the intel support here: https://community.intel.com/t5/Ethernet-Products/E810-C-does-not-forward-lldp/m-p/1268044/highlight/true#M24638
This forum did not point me to the right solution, it was a private chat at the end.

**Comment by vincentbernat** [comment]
I may not have helped by hijacking the issue with the LLDP in firmware issue, but from my understanding, the ice driver does not allow to disable the LLDP in firmware: no private flag, no debugfs "command" file. In go-lldp, I see that you are only disabling LLDP in firmware for i40e, not ice. So, do we need to disable LLDP in firmware for ice and how?

**Comment by majst01** [comment]
yes, disable-firmware-lldp is not required for ice.ko

**Comment by vincentbernat** [comment]
FI, disabling through ethtool is unsupported on many firmwares. Kernel says:

```c
	/* If the driver detected FW LLDP was disabled on init, this flag could
	 * be set, however we do not support _changing_ the flag:
	 * - on XL710 if NPAR is enabled or FW API version < 1.7
	 * - on X722 with FW API version < 1.6
	 * There are situations where older FW versions/NPAR enabled PFs could
	 * disable LLDP, however we _must_ not allow the user to enable/disable
	 * LLDP with this flag on unsupported FW versions.
	 */
```

It's a bit mysterious why this is possible through sysfs. So, I keep using sysfs instead.
