### ISSUE TITLE
How to compile for Android

### ISSUE THREAD

**Issue by bayssmekanique** [lldpd/lldpd#446]
This is not an issue, but just a quick explainer of some of the finer points that are not easily figured out from the documentation on how to compile this library for Android.  FWIW, I was able to successfully build this tool without any modifications on a Windows PC using the Ubuntu WSL.

1) Don't clone the repo or download the `master` branch from GitHub.  Instead, download the `tar` from the website: [https://lldpd.github.io/installation.html#install-from-source](https://lldpd.github.io/installation.html#install-from-source)

2) Install `automake`, `libtool`, and `pkg-config`. (`sudo apt-get install automake libtool pkg-config`)

3) Download the NDK as directed in the instructions.  The current LTS is `v21`, so you'll need to go down the page to the Stable `v22`  release and download it.

4) In the root of the `lldp` directory, make a blank `compile.sh` file. (`touch compile.sh`). Copy the scripts from the Android section of the readme into this file:
```sh
export TOOLCHAIN=$PWD/toolchains/llvm/prebuilt/linux-x86_64
export TARGET=aarch64-linux-android
export API=24

export AR=$TOOLCHAIN/bin/llvm-ar
export CC=$TOOLCHAIN/bin/$TARGET$API-clang
export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
export LD=$TOOLCHAIN/bin/ld
export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
export STRIP=$TOOLCHAIN/bin/llvm-strip
export AS=$CC
./autogen.sh
mkdir -p build && cd build
../configure \
    --host=$TARGET \
    --with-sysroot=$TOOLCHAIN/sysroot \
    --prefix=/system \
    --sbindir=/system/bin \
    --runstatedir=/data/data/lldpd \
    --with-privsep-user=root \
    --with-privsep-group=root \
    PKG_CONFIG=/bin/false
make
make install DESTDIR=$PWD/install
```

5) Find the `llvm` prebuilt directory and change the `TOOLCHAIN` variable of the script to match the path where the `linux-x86_64` directory resides.

```sh
export TOOLCHAIN=/mnt/c/Users/Zach/Downloads/android-ndk-r22b-linux-x86_64/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64
```

6) Determine the CPU architecture you are targeting (`adb shell getprop ro.product.cpu.abi`). Change the `TARGET` variable to match the target architecture. There will be a trailing suffix to the target name, so I'd recommend looking in the `linux-x86_64/bin` directory for the `clang` file that starts with the CPU architecture you are targeting.
```
C:\Users\Zach> adb shell getprop ro.product.cpu.abi
armeabi-v7a
```
```sh
export TARGET=armv7a-linux-androideabi
```

7) Set the `API` variable to your target API.  Check in the same `linux-x86_64/bin` to ensure the API you are targeting has a supported `clang` file with that version. As of this writing, there appears to be support for API 21-30 included for most architectures.
```sh
export API=29
```

8) At this point your script should look something like this:
```sh
export TOOLCHAIN=/mnt/c/Users/Zach/Downloads/android-ndk-r22b-linux-x86_64/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64
export TARGET=armv7a-linux-androideabi
export API=29

export AR=$TOOLCHAIN/bin/llvm-ar
export CC=$TOOLCHAIN/bin/$TARGET$API-clang
export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
export LD=$TOOLCHAIN/bin/ld
export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
export STRIP=$TOOLCHAIN/bin/llvm-strip
export AS=$CC
./autogen.sh
mkdir -p build && cd build
../configure \
    --host=$TARGET \
    --with-sysroot=$TOOLCHAIN/sysroot \
    --prefix=/system \
    --sbindir=/system/bin \
    --runstatedir=/data/data/lldpd \
    --with-privsep-user=root \
    --with-privsep-group=root \
    PKG_CONFIG=/bin/false
make
make install DESTDIR=$PWD/install
```

You should be ready to run the script (`./compile.sh`). Follow the instructions in the `README` for moving the install files to the correct locations on your device and you should be up and running.

----
@vincentbernat, please close this issue at your convenience.

**Comment by vincentbernat** [comment]
You can do a pull request against the README to add the missing information if you want.
