### ISSUE TITLE
How MgmtIP be selected?

### ISSUE THREAD

**Issue by guking3** [lldpd/lldpd#450]
The remote device's config IP address is as belove:
eth0                   172.17.9.240/24      up/up         N/A             N/A
lo                     127.0.0.1/16         up/up         N/A             N/A
                        1.1.1.240/32         up/up         N/A             N/A
# Bug description
But, in the neighbor message,the MgmtIP is 1.1.1.240,not 172.17.9.240

Interface:    ep135, via: LLDP, RID: 4, Time: 0 day, 00:22:08
  Chassis:     
    ChassisID:    mac *****
    SysName:      240
    SysDescr:     *********
    TTL:          120
    MgmtIP:       1.1.1.240
    MgmtIP:       fe80::b445:f8ff:feff:490
    Capability:   Bridge, on
    Capability:   Router, on
    Capability:   Wlan, off
    Capability:   Station, off
  Port:        
    PortID:       local ep135
    PortDescr:    ep135

**Comment by vincentbernat** [comment]
It's the first IP address lldpd can detect. Usually, following the index order but if the first interface gets its IP address later (DHCP), it may miss it. You can either run lldpd with `-m eth0` or you can use `configure system ip management pattern eth0`.

**Comment by guking3** [comment]
Hello expert：
       It's my pleasure to receive your reply.I tried your method to "configure system ip management pattern eth0", but after this, the MgmtIP would not display.As belove:
remote device:
show ip interfaces 
Interface    Master    IPv4 address/mask    Admin/Oper    BGP Neighbor    Neighbor IP
-----------  --------  -------------------  ------------  --------------  -------------
eth0                   172.17.19.50/24      up/up         N/A             N/A
lo                     127.0.0.1/16         up/up         N/A             N/A
                       2.2.2.50/32          up/up         N/A             N/A
[lldpcli] # configure system ip management pattern eth0

Then show the lldp neighbors
Interface:    ep115, via: LLDP, RID: 2, Time: 0 day, 00:04:15
  Chassis:     
    ChassisID:    mac ******
    SysName:      sonic
    SysDescr:    ***
    TTL:          120
    Capability:   Bridge, on
    Capability:   Router, on
    Capability:   Wlan, off
    Capability:   Station, off
  Port:        
    PortID:       local ep115
    PortDescr:    ep115

My branch version is 0.9.6, is it a known issues in this version？Best Regards, Thank you

**Comment by vincentbernat** [comment]
Yes, it requires 1.0.5.

**Comment by vincentbernat** [comment]
Alternatively, if you know your management address will start with `172.17`, you can use `172.17.*` instead of `eth0`.

**Comment by guking3** [comment]
Thank you very much！
