### ISSUE TITLE
[LLDPD][Feature question] Ignoring incoming LLDP frames not matching a certain host pattern.

### ISSUE THREAD

**Issue by LaurentDumont** [lldpd/lldpd#451]
# Bug description

## Steps to reproduce the problem

- EVPN VXLAN fabric
- End hosts are receiving multiple LLDP frames on a single port.
- End hosts are showing each of those hosts as a neighbor.

 
## Expected outcome

Ideally, we would filter the frames at the network level to prevent them from getting to the end hosts themselves.

That said, we we're wondering if LLDP itself could be set to ignore certain neighbors based on sysName patterns? I see that there is a filter fonction that seems to be built around picking between CDP/LLDP.

**Comment by vincentbernat** [comment]
Isn't it better to ignore VXLAN interfaces?

**Comment by LaurentDumont** [comment]
> Isn't it better to ignore VXLAN interfaces?

This is what I was looking for but we are seeing the neighbors on non vxlan interfaces. I'm trying to find a pattern but we are seeing the physical 10G interface from other end-hosts across the fabric.

Not all the time but when I do, tcpdump-ing the traffic shows the LLDP frames advertised from the non-vxlan physical 10G interfaces 🤔

What I am not 100% sure is what is the default behavior for multicast MAC inside the EVPN topology. It should be forwarded across all hosts but I figured all of my hosts would see everyone else inside the layer2 fake-topology.

I'll dig in this a bit more, we can close this issue if you want!

**Comment by vincentbernat** [comment]
If you plug the VXLAN on a bridge, the bridge should not forward LLDP frames by default. Moreover, lldpd only look for incoming frames: use `tcpdump --direction=in` to emulate this. It may mean that you have an equipment forwarding the LLDP frame on the same network.

**Comment by vincentbernat** [comment]
Let's close this one.
