### ISSUE TITLE
No neighbour is shown

### ISSUE THREAD

**Issue by ArpStorm1** [lldpd/lldpd#455]
Hi everyone, 
I have one server that even though it is connected properly, I can't see any neighbour of it at all.

```
# lldpcli -vv
lldpcli 1.0.1
Built on 2018-08-12T14:47:39Z

```

# Bug description
I am trying to run the command ``` lldpcli show neig ``` and it results with no neighbors at all.
I have a other servers from that type with the same hardware and I'm having problems only with one server...
I've already tried to reinstall it, and notging :(
## Steps to reproduce the problem
I really don't know... All the other servers works fine.
 
## Expected outcome
lldpcli should return a list of neighbors.

**Comment by vincentbernat** [comment]
What's the output of `ethtool -i XXXX` (`XXXX` being the interface name)? Likely to be an Intel card. See https://github.com/lldpd/lldpd/blob/1.0.1/README.md#troubleshooting for the workaround.

**Comment by ArpStorm1** [comment]
No. It is a mellanox card.
``` 
ethtool -i ens7f0
driver: mlx5_core
version: 5.0-0
firmware-version: 14.27.4000 (HP_2420110034)
expansion-rom-version: 
bus-info: 0000:af:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes
```

**Comment by vincentbernat** [comment]
Try the tcpdump command to see if you get incoming packets.

**Comment by ArpStorm1** [comment]
It seems that lldp packets are sent to the switch, but there is no response...

**Comment by vincentbernat** [comment]
Try again without `-p` and see if you get the answers.

**Comment by ArpStorm1** [comment]
Still :( 
I can see that all the messages are send with System Description TLV which consists the term "Red Hat enterprise Linux", so it looks like all the messages are sent from the server, but no message are accepted from the switch

**Comment by vincentbernat** [comment]
So, it looks like the switch is not sending anything. AFAIK, Mellanox does not intercept LLDP packets.

**Comment by ArpStorm1** [comment]
I have other servers with the exact NIC and the exact firmware & driver. All works fine there.
Maybe there is a way to check if the kernel drops these packets?

**Comment by vincentbernat** [comment]
On Linux, tcpdump extracts packet very early. Only the driver runs earlier. Are you sure that LLDP is not just disabled on the switch port this server is connected to?

**Comment by ArpStorm1** [comment]
Hi, so after switch debugging we discovered some issue there which dropped the lldp packets. So everything is working! Thank you!!!
