### ISSUE TITLE
I am fresher in lldpd. When I try to cross compile in my Linux pc i got following error.

### ISSUE THREAD

**Issue by ndivakaran** [lldpd/lldpd#458]
make[4]: Entering directory '/home/costar/Platform/Liberty/V2.1/3rdPartyLibrarySource/lldpd/lldpd-1.0.5/libevent'
  GEN      include/event2/event-config.h
make  all-am
make[5]: Entering directory '/home/costar/Platform/Liberty/V2.1/3rdPartyLibrarySource/lldpd/lldpd-1.0.5/libevent'
  CC       sample/dns-example.o
  CC       buffer.lo
  CC       bufferevent.lo
  CC       bufferevent_filter.lo
  CC       bufferevent_pair.lo
  CC       bufferevent_ratelim.lo
  CC       bufferevent_sock.lo
  CC       event.lo
  CC       evmap.lo
  CC       evthread.lo
  CC       evutil.lo
  CC       evutil_rand.lo
  CC       evutil_time.lo
  CC       listener.lo
  CC       log.lo
  CC       strlcpy.lo
  CC       select.lo
  CC       poll.lo
  CC       epoll.lo
  CC       signal.lo
  CC       evdns.lo
  CC       event_tagging.lo
  CC       evrpc.lo
  CC       http.lo
  CCLD     libevent.la
  CCLD     sample/dns-example
  CC       sample/event-read-fifo.o
  CCLD     sample/event-read-fifo
  CC       sample/hello-world.o
  CCLD     sample/hello-world
  CC       sample/http-server.o
  CCLD     sample/http-server
  CC       sample/http-connect.o
  CCLD     sample/http-connect
  CC       sample/signal-test.o
  CCLD     sample/signal-test
  CC       sample/time-test.o
  CCLD     sample/time-test
  CCLD     libevent_core.la
  CCLD     libevent_extra.la
make[5]: Leaving directory '/home/costar/Platform/Liberty/V2.1/3rdPartyLibrarySource/lldpd/lldpd-1.0.5/libevent'
make[4]: Leaving directory '/home/costar/Platform/Liberty/V2.1/3rdPartyLibrarySource/lldpd/lldpd-1.0.5/libevent'
  CC       liblldpd_la-event.lo
  CC       liblldpd_la-lldpd.lo
lldpd.c: In function ‘lldpd_hide_ports’:
lldpd.c:957:5: warning: ‘strncat’ specified bound 2 equals source length [-Wstringop-overflow=]
  957 |     strncat(buffer, ", ", 2);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
  CC       liblldpd_la-pattern.lo
  CC       liblldpd_la-bitmap.lo
  CC       protocols/liblldpd_la-lldp.lo
  CC       protocols/liblldpd_la-cdp.lo
  CC       protocols/liblldpd_la-sonmp.lo
  CC       protocols/liblldpd_la-edp.lo
  CC       liblldpd_la-forward-linux.lo
  CC       liblldpd_la-interfaces-linux.lo
  CC       liblldpd_la-netlink.lo
  CC       liblldpd_la-dmi-linux.lo
  CC       liblldpd_la-priv-linux.lo
  CCLD     liblldpd.la
copying selected object files to avoid basename conflicts...
  CCLD     lldpd
  GEN      lldpd.8
  GEN      lldpd.service
  GEN      lldpd.sysusers.conf
make[3]: Leaving directory '/home/costar/Platform/Liberty/V2.1/3rdPartyLibrarySource/lldpd/lldpd-1.0.5/src/daemon'
make[2]: Leaving directory '/home/costar/Platform/Liberty/V2.1/3rdPartyLibrarySource/lldpd/lldpd-1.0.5/src/daemon'
Making all in src/lib
make[2]: Entering directory '/home/costar/Platform/Liberty/V2.1/3rdPartyLibrarySource/lldpd/lldpd-1.0.5/src/lib'
  CC       errors.lo
  CC       connection.lo
  CC       atom.lo
  CC       helpers.lo
  CC       atoms/config.lo
  CC       atoms/dot1.lo
  CC       atoms/dot3.lo
  CC       atoms/interface.lo
  CC       atoms/med.lo
  CC       atoms/mgmt.lo
  CC       atoms/port.lo
  CC       atoms/custom.lo
  CC       atoms/chassis.lo
  GEN      atom-glue.c
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/config.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/dot1.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/dot3.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/interface.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/med.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/mgmt.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/port.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/custom.c:19:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/chassis.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/config.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/dot1.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/dot3.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/interface.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/med.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/mgmt.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/port.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/custom.c:19:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/aarch64-oclea-linux/usr/include/sys/cdefs.h:452,
                 from /usr/local/aarch64-oclea-linux/usr/include/features.h:465,
                 from /usr/local/aarch64-oclea-linux/usr/include/bits/libc-header-start.h:33,
                 from /usr/local/aarch64-oclea-linux/usr/include/stdio.h:27,
                 from ./atoms/chassis.c:18:
/usr/local/aarch64-oclea-linux/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
   23 | #error "__WORDSIZE is not defined"
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [Makefile:942: atom-glue.c] Error 1
make[2]: Leaving directory '/home/costar/Platform/Liberty/V2.1/3rdPartyLibrarySource/lldpd/lldpd-1.0.5/src/lib'
make[1]: *** [Makefile:621: all-recursive] Error 1
make[1]: Leaving directory '/home/costar/Platform/Liberty/V2.1/3rdPartyLibrarySource/lldpd/lldpd-1.0.5'
make: *** [Makefile:510: all] Error 2

**Comment by vincentbernat** [comment]
Sorry, not a bug in lldpd. There is no `__WORDSIZE` in lldpd source code. So, either your headers are incorrect or your toolchain is mangled.

**Comment by ndivakaran** [comment]
@vincentbernat  thank you for the valid comment.
