### ISSUE TITLE
not receiving neighbors info.

### ISSUE THREAD

**Issue by SandipJunghare** [lldpd/lldpd#461]
This is an example of bug report. Try to adapt it to your case. When
putting code snippets (logs, commands), put them between triple backquotes:

```
# show neighbors
![Screenshot from 2021-07-30 17-43-18](https://user-images.githubusercontent.com/88190551/127651555-3e98b617-d19f-4b7a-9717-b1716d77bb79.png)

```

 not able to receive neighbors data and both laptops having the same lldpd library.
what exact command need to execute to start receiving lldpd frames??
currently i am using "resume"  command to receive/transmit data.
Screenshot is attached for reference.

**Comment by SandipJunghare** [comment]
![Screenshot from 2021-07-30 17-43-18](https://user-images.githubusercontent.com/88190551/127652167-0dc98b7d-1c36-43eb-8110-1ab6c0340c44.png)

**Comment by vincentbernat** [comment]
Sorry, you did not provide any actionable data. Be sure to install lldpd as stated in the documentation and there is no need to use `resume`. The documentation and the bug report template also contains some basic troubleshooting information. I am closing this bug report as this is unlikely to be a bug in lldpd. If `tcpdump` is unable to see a LLDP packet, lldpd cannot do that either.

**Comment by SandipJunghare** [comment]
![Screenshot from 2021-07-30 17-43-18](https://user-images.githubusercontent.com/88190551/127652394-506be083-f0dc-43ec-b95f-f89ea279f084.png)
![Screenshot from 2021-07-30 17-43-18](https://user-images.githubusercontent.com/88190551/127654925-8a5e3f13-abdd-42a3-bde6-37fcabcd0fcb.png)

**Comment by SandipJunghare** [comment]
Hi vincent,
provide the screenshot for your reference.
I get information for all other commands except for "show statistics and show neighbors".

Installation done as per github readme doc.
![Screenshot from 2021-07-30 17-43-18](https://user-images.githubusercontent.com/88190551/127655543-94b0d44a-ce8c-47e2-9039-4e5395820f13.png)
![Screenshot from 2021-07-30 17-43-18](https://user-images.githubusercontent.com/88190551/127655575-151d00c0-896e-4e72-8982-8b782edd22bc.png)

**Comment by vincentbernat** [comment]
Provide the result for `tcpdump`. Running inside a virtual machine usually means you can't see neighbors because they are not local (there is some kind of bridge in the path).

**Comment by SandipJunghare** [comment]
![Screenshot from 2021-07-30 20-12-34](https://user-images.githubusercontent.com/88190551/127674052-5297efd1-c4dc-4ed9-a14b-83bd92946210.png)
![Screenshot from 2021-07-30 20-24-01](https://user-images.githubusercontent.com/88190551/127674079-717fa95b-429e-4949-99eb-243033eedf84.png)
![Screenshot from 2021-07-30 20-32-38](https://user-images.githubusercontent.com/88190551/127674098-f906e3f8-58fa-456b-beb8-3d821920c920.png)

**Comment by vincentbernat** [comment]
In the last capture, you see the the LLDPU that is sent by lldpd. You should also see the ones that are received. If you don't see them, it means you have no neighbors. What neighbor do you expect to see and how is it connected to your virtualbox?

**Comment by SandipJunghare** [comment]
hi,
i expect to see the other virtual box computer connected using ethernet/LAN cable.

**Comment by vincentbernat** [comment]
If there is a switch between them (physical or virtual), the neighbor is the switch. So, it's expected that you don't see anything.

**Comment by SandipJunghare** [comment]
hi,
So you mean to say, i need two dedicated linux computers to receive LLDPU not the computers running virtual box in them?
Sorry, if i am repeating my question.

Thanks.

**Comment by vincentbernat** [comment]
Yes. There may be a way to make it work with Virtualbox, but I don't know how. It's far easier to have two computers attached directly one to another (no switch between them).
