### ISSUE TITLE
issue in opening lldpcli application in sudo mode.

### ISSUE THREAD

**Issue by SandipJunghare** [lldpd/lldpd#463]
Hi,

not able to open lldpcli application in sudo mode so could not connect with sockets and can't retrieve data like show chassis.
I read other issues thread to resolve this kind of issue and executed the commands as well but still it persists.
Attaching screenshot for your reference.
![error](https://user-images.githubusercontent.com/88190551/128993132-50d12f39-499e-4d71-bf8e-7369077f135d.png)

Thanks.

**Comment by vincentbernat** [comment]
Hello Sandip,

This is still not a bug report. `show chassis` do not require to be root. You don't even show the result of the command in your screenshot. Likely you don't get the root prompt because the socket does not exist, so lldpcli is not able to determine if you have the appropriate rights or not.

Please, stop opening bug reports just to get support.

**Comment by SandipJunghare** [comment]
Hi vincent.
Sure i will not open issues in bug report. Pardon me, if i am making wrong bug reports.

I attached the screenshot again.
Even though i clone lldpd pckg from git still i get the same error and i followed the steps mentioned in readme.
i also took reference of issue   https://github.com/lldpd/lldpd/issues/205

At start, the errors i faced were same as issue#205. I followed those steps to rectify. But still persist.

In screenshot, the lldpd.socket file, i created giving full rights to it.

I have raised this issue with my IT team for sudo access while running lldpcli executable.


thanks.

![error2](https://user-images.githubusercontent.com/88190551/129001675-ea7095dc-e712-4208-839e-b32c9a4edeb3.png)

**Comment by vincentbernat** [comment]
You have one version of lldpd running (the one shipped with the system I think) and one that you did compile with different options. Do not run lldpd from systemd, run it from another terminal.

**Comment by SandipJunghare** [comment]
hi vincent,
I am able to read everything on neighbor device data. I mostly followed previous bug reports to solve my socket/root problems and off-course thanks for suggestions.

Can i get to read the topology of network my device is connected to??  Or do i have to create a TLV for that on network/device?

Also, for system capability (i.e. router/bridge ) how you decided because in code, i see that only two key values are there i.e. enable and available.?
tag_attr(w,"type", "", symbol); ---   kind of function you used for deciding.   Is this function calls any other API to collect capability info??


Pardon me, if questions are irrelevant.


Thanks.

**Comment by SandipJunghare** [comment]
Hi Vincent,

i am able to implement all the functionality needed for my application using lldpd.
Thanks for your support.

Sandip.
