### ISSUE TITLE
unable to send packet on real device for <interface>: No buffer space available

### ISSUE THREAD

**Issue by sthen** [lldpd/lldpd#474]
I'm running lldpd on OpenBSD. In some cases, it spams syslog with `unable to send packet on real device for <interface>: No buffer space available`.

```
2021-08-29T13:36:23 [ DBG/alloc] general configuration cleanup
2021-08-29T13:36:23 [ DBG/event] trigger sending PDU for port ix0
2021-08-29T13:36:23 [ DBG/send] send PDU on ix0
2021-08-29T13:36:23 [ DBG/send] fallback to protocol LLDP for ix0
2021-08-29T13:36:23 [ DBG/lldp] send LLDP PDU to ix0
2021-08-29T13:36:23 [ DBG/interfaces] send PDU to ethernet device ix0 (fd=7)
2021-08-29T13:36:23 [WARN/lldp] unable to send packet on real device for ix0: No buffer space available
2021-08-29T13:36:23 [ DBG/event] trigger sending PDU for port ix1
2021-08-29T13:36:23 [ DBG/send] send PDU on ix1
2021-08-29T13:36:23 [ DBG/send] fallback to protocol LLDP for ix1
2021-08-29T13:36:23 [ DBG/lldp] send LLDP PDU to ix1
2021-08-29T13:36:23 [ DBG/interfaces] send PDU to ethernet device ix1 (fd=8)
2021-08-29T13:36:23 [WARN/lldp] unable to send packet on real device for ix1: No buffer space available
```

Where I have seen this, it has been on machines with longer uptime where lldpd has been attempting to send on an interface which is ifconfig'd up but has no link. Trying to reproduce the problem on another machine with low tx-interval it isn't by itself sufficient to trigger the problem at least in a short-ish time so maybe something else is needed. I do have a machine in this state I can test diffs on if wanted.

Poor diff to hide the symptom:

```
Index: src/daemon/protocols/lldp.c
--- src/daemon/protocols/lldp.c.orig
+++ src/daemon/protocols/lldp.c
@@ -505,8 +505,9 @@ end:
 
 	if (interfaces_send_helper(global, hardware,
 		(char *)packet, pos - packet) == -1) {
-		log_warn("lldp", "unable to send packet on real device for %s",
-		    hardware->h_ifname);
+		if (errno != ENOBUFS)
+			log_warn("lldp", "unable to send packet on real device for %s",
+			    hardware->h_ifname);
 		free(packet);
 		return ENETDOWN;
 	}
```

A better fix on OpenBSD would be to check LINK_STATE_IS_UP on if_msghdr.ifm_data.ifi_link_state from RTM_IFINFO route socket messages to avoid sending on interface known to be down (the macro includes various states marking either "up" or "unknown").

# Additional information

 - Output of `lldpd -vv`:

```
lldpd 1.0.12
  Built on 2021-08-29T11:55:50Z

Additional LLDP features:    LLDP-MED, Dot1, Dot3, Custom TLV
Additional protocols:        CDP, FDP, EDP, SONMP
SNMP support:                no
Privilege separation:        enabled
Privilege separation user:   _lldpd
Privilege separation group:  _lldpd
Privilege separation chroot: /var/run/lldpd
Configuration directory:     /etc

C compiler command: cc  -Wunknown-warning-option -fdiagnostics-show-option -fdiagnostics-color=auto -pipe -Wall -W -Wextra -Wformat -Wformat-security -Wimplicit-fallthrough -Wfatal-errors -Wheader-guard -Wdocumentation -Winline -Wpointer-arith -fno-omit-frame-pointer -Wno-cast-align -Wno-unused-parameter -Wno-missing-field-initializers -Wno-sign-compare -fstack-protector -fstack-protector-all -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -O2 -pipe -g -fstack-protector-all  -I/usr/local/include
Linker command:     /usr/bin/ld  -Wl,-z,relro -Wl,-z,now  -g -L/usr/local/lib 
```

 - Output of `ps -fp $(pgrep -d, -x lldpd)`:

```
$ ps alxw|grep -e PPI[D] -e lldp[d] 
  UID   PID  PPID CPU PRI  NI   VSZ   RSS WCHAN   STAT   TT       TIME COMMAND
    0 78621     1   0   2   0   876  1376 netio   I      ??    0:00.01 lldpd: monitor. (lldpd)
  720 87340 78621   0   2   0   904  1576 kqread  S      ??    0:00.05 lldpd: 3 neighbors. (lldpd)
```

 - Output of `uname -sro`:

```
$ uname -mrsv
OpenBSD 6.9 GENERIC.MP#473 amd64
```

**Comment by vincentbernat** [comment]
Hey!

Thanks for the report. If I understand correctly, the problem persists after restarting lldpd.

On BSD, any change received about RTM_IFINFO triggers a rescan of all interfaces to check their state. If your interface has no link, the right fix would be to understand why lldpd does not detect it as such. It relies on flags attached to the interface. If `IFF_RUNNING` is set, the port is considered up and with a link. What do you get with `ifconfig ix0`?

**Comment by sthen** [comment]
Correct, it persists after restarting lldpd. (Bringing the interface down and back up clears it, at least for a while). IFF_RUNNING doesn't indicate link state; in if.h the comment says "resources allocated" and looking at a few drivers it usually seems set after init is done (descriptors/interrupts setup, filters programmed etc) so, shortly after IFF_UP in most cases.

```
$ ifconfig ix0
ix0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	lladdr ac:1f:6b:64:a9:10
	index 1 priority 0 llprio 3
	media: Ethernet autoselect
	status: no carrier
```

**Comment by vincentbernat** [comment]
OK. For Linux, it says "interface RFC2863 OPER_UP". Looking at how `ifconfig.c` does, could you try this patch?

```patch
diff --git a/src/daemon/interfaces-bsd.c b/src/daemon/interfaces-bsd.c
index f21bad1a6f4e..8361278e4b8b 100644
--- a/src/daemon/interfaces-bsd.c
+++ b/src/daemon/interfaces-bsd.c
@@ -433,6 +433,8 @@ ifbsd_extract(struct lldpd *cfg,
                    "grabbing information on interface %s",
                    ifaddr->ifa_name);
                device = ifbsd_extract_device(cfg, ifaddr);
+               if (!LINK_STATE_IS_UP(ifaddr->ifa_data->ifi_link_state))
+                       device->flags &= ~IFF_RUNNING;
                if (device)
                        TAILQ_INSERT_TAIL(interfaces, device, next);
                break;

```

I would still need to check if it works for FreeBSD/NetBSD.

**Comment by sthen** [comment]
Great, 922b3fb68eebf works, many thanks Vincent!

**Comment by vincentbernat** [comment]
OK, let's make it conditional on OpenBSD. Maybe other BSD are using `IFF_RUNNING` like Linux.

**Comment by sthen** [comment]
I found a freenas box to check (based on FreeBSD 11.3), it has the same flag use for RUNNING, their check macro is a little different though (it's RT_LINK_IS_UP and is hidden behind #ifdef _KERNEL, it checks interface capabilities for LINKSTATE rather than checking >= LINK_STATE_UP || LINK_STATE_UNKNOWN, I think it's likely your LINK_STATE_IS_UP macro will work but would be safer if someone using FreeBSD for real can check that).

NetBSD has the same meanings for LINK_STATE_UP / LINK_STATE_UNKNOWN etc as Open, just doesn't have the check macro (iirc we added the macro mainly to simplify the check with the dynamic routing daemons). Pretty sure it will be safe there as-is.

```
root@nas2:~ # uname -v
FreeBSD 11.3-RELEASE-p7 #0 r325575+ca0f1a6ba25(HEAD): Tue Apr 21 20:46:20 UTC 2020     root@tnbuild01.tn.ixsystems.com:/freenas-releng/freenas/_BE/objs/freenas-releng/freenas/_BE/os/sys/FreeNAS.amd64 
root@nas2:~ # ifconfig bce1
bce1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=c01bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,VLAN_HWTSO,LINKSTATE>
	ether 00:26:b9:5d:24:e5
	hwaddr 00:26:b9:5d:24:e6
	nd6 options=9<PERFORMNUD,IFDISABLED>
	media: Ethernet autoselect (none)
	status: no carrier
root@nas2:~ # ifconfig bce1
bce1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=c01bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,VLAN_HWTSO,LINKSTATE>
	ether 00:26:b9:5d:24:e5
	hwaddr 00:26:b9:5d:24:e6
	nd6 options=9<PERFORMNUD,IFDISABLED>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
```

**Comment by vincentbernat** [comment]
I am more worried about the cast for `struct if_data`. I'll spawn a VM to check.

**Comment by vincentbernat** [comment]
Well, I don't remember what I did. Let's consider it's OK now.
