### ISSUE TITLE
Is there a way to setup enabled capabilities?

### ISSUE THREAD

**Issue by ingmaf** [lldpd/lldpd#499]
Hello,

I have a linux box acting as a router so I'd like to advertise `Router` as a Enabled Capability. Without any modification the daemon is advertising `Station Only` as the only Enabled Capability.

Thanks for your answer.
Regards.

**Comment by vincentbernat** [comment]
Currently, this is hard coded. You get "Router" if IPv4 forwarding is globally enabled.

**Comment by ingmaf** [comment]
Confirmed. I've just changed `net.ipv4.ip_forward=1` on my box and `Router` capability is now `on`.
Thank you very much Vincent!
