### ISSUE TITLE
Send MFS based on configured interface MTU

### ISSUE THREAD

**Issue by devicenull** [lldpd/lldpd#511]
I see support in the code for actually sending MFS as part of the LLDP advertisement packets, however I can't actually find any code that sets lldpd_port.p_mfs outside of tests.

I'd like to see p_mfs get set to the same value as MTU - I think this is the correct behavior here?

**Comment by vincentbernat** [comment]
It was done like that in the past but MFS is not MTU. Linux does not have a way to expose MFS.

**Comment by vincentbernat** [comment]
I'll close this one. Linux does not expose MFS. MTU is not MFS.
