### ISSUE TITLE
lldpcli is taking more than two minutes to complete "unconfigure lldp vlan-tx"

### ISSUE THREAD

**Issue by muraliadiga** [lldpd/lldpd#518]
#After upgrading from lldpd-1.0.3 to 1.0.8, I have seen that vlan 0 gets assigned to each port gets attached/configured to lldpd.
We don't want to send lldpdu with vlan. 

I know that we can use "unconfigure lldp vlan-tx". But configuring it via lldpcli takes more than 2 minutes which makes our synchronous call (via lldpcli to configure lldpd) blocks for more than 2 mins which is not excepted.

Is there a known issue and it got fixed in version greater than 1.0.8?
I see below one fix related to vlan 0 . Does this solve my issue?

lldpd (1.0.13)
 * Fix:
   + Add support for 2.5G, 5G, 25G and 50G based Ethernet (#475)
   + Fix link-down detection on OpenBSD (#476)
   + Fix LLDP packets encapsuled in VLAN 0 in some conditions

```
# lldpcli -vv
lldpcli 1.0.8

[lldpcli] # show int
-------------------------------------------------------------------------------
LLDP interfaces:
-------------------------------------------------------------------------------
Interface:    lldp-Eth1_1, via: LLDP, Time: 0 day, 00:23:28
  Chassis:     
    ChassisID:    mac xx:xx:xx:xx:xx:xx
    SysName:      abcdef
    SysDescr:     abcdef
    MgmtIP:       X.X.X.X
    MgmtIface:    16
    MgmtIP:       fd00:0:0:1::3
    MgmtIface:    5
    Capability:   Bridge, on
    Capability:   Router, on
    Capability:   Wlan, off
    Capability:   Station, off
  Port:        
    PortID:       ifname lldp-Eth1_1
    PortDescr:    Ethernet1/1
    VlanTX:       VID: 0, Prio: 0, DEI: 0
  TTL:          120


```

**Comment by vincentbernat** [comment]
Yes, 1.0.13 should fix the issue with VLAN 0.

The fact that lldpcli takes 2 minutes is not expected. Is it for all commands? Does `getent hosts $(uname -n)` also takes the same time?

**Comment by vincentbernat** [comment]
Let's close this one because of no feedback.
