### ISSUE TITLE
RFC 3041 addresses reported as MgmtIP

### ISSUE THREAD

**Issue by 0n-s** [lldpd/lldpd#521]
# Bug description
RFC 3041 (also known as IPv6 privacy extensions, not to be confused with stable privacy addresses...which also officially have "Privacy Extensions" in their name, sigh) addresses are selected by lldpd to advertise an IPv6 `MgmtIP`. This should not happen, as these addresses are mainly for outgoing connections (correct me if I'm wrong), & are not stable.

## Steps to reproduce the problem
(Linux instructions)
1. `sysctl -w net.ipv6.conf.eth0.use_tempaddr = 2` (enables Privacy Extensions for `eth0`)
2. wait for a temporary address to show up on the interface, like (output from `ip -6 addr`):
```
inet6 2001:db8:0:1:8992:3c03:d6e2:ed72/64 scope global temporary dynamic
   valid_lft 32258sec preferred_lft 5157sec
```
(note the `temporary` tag)
3. tell lldpd to send an LLDPDU to the network.
## Expected outcome
lldpd should ignore addresses with the `temporary` property in its IP address autoselection.

NB: temporary addresses are necessarily mangled from stable addresses; therefore, if there were temporary addresses, there are stable addresses to fall back onto; see the output of `ip -6 addr show primary`. In any situation where lldpd automatically found an IPv6 `MgmtIP` currently, it will continue to be able to do so even if it ignores all temporary addresses.

## Current outcome
Unless the management IP is overriden with `-m`, lldpd will in all likelihood select the current temporary address, since in the `ip -6 addr` listing temporary addresses come 1st, then public addresses.

**Comment by vincentbernat** [comment]
Thanks. This should be fixed in db5c70856ad5.
