### ISSUE TITLE
Override system capabilities TLV Type 7

### ISSUE THREAD

**Issue by igsanchez** [lldpd/lldpd#522]
Is it possible to override the existing system capabilities?

Imagine that someone wants to report "Capability: Station, on", but they have "Capability:   Bridge, on". Why not let the user configure or override it.

**Comment by vincentbernat** [comment]
Currently not possible. Patch welcome.

**Comment by avlec** [comment]
Resolved with that PR merging?

**Comment by vincentbernat** [comment]
Thanks!
