### ISSUE TITLE
Management IP from Network Interface

### ISSUE THREAD

**Issue by avlec** [lldpd/lldpd#523]
# Feature Description
The ability to specify an interface or an interface pattern as the source for a management IP address.
## Multiple matching Patterns
Use the first interface to match the pattern specified.
## Interfaces with Multiple Addresses
Using the first address might be sufficient however, conjoining this with the pattern that can be set through `lldpcli configure system ip management <pattern>` could probably be used as a secondary filter. Then the first match from that would be used.
## Interfaces with Dynamic Addresses
Should support interfaces with non-static addresses.

**Comment by vincentbernat** [comment]
AFAIK `configure system ip management pattern` can match an interface name. So, it would match your need, wouldn't it?

**Comment by avlec** [comment]
The build tool I'm using seems to be referencing 1.0.4, I saw here that this should work in 1.0.5 #450

**Comment by avlec** [comment]
Confirmed that the address is being fetched on 1.0.5. I think the docs should be more clear that the pattern can be used to for retrieval of the address from interfaces. The docs on the website make it sound like only IP addresses can be used, it does reference the interfaces section but reading that seems to leave me with the impression that wildcards are the only thing that carries over.
