### ISSUE TITLE
Pause in Configuration should result in Paused lldpd

### ISSUE THREAD

**Issue by avlec** [lldpd/lldpd#538]
When putting code snippets (logs, commands), put them between triple
backticks:

```
# lldpcli -vv
[output of lldpcli -vv]
```

# Bug description

## Steps to reproduce the problem

 1. Add pause to /etc/lldpd.conf
 2. Restart system or reload lldpd

## Expected outcome

`lldpd` should be paused

## Current outcome

`lldpd` is not paused

# Additional information

 - Output of `lldpd -vv`:

```
lldpd 1.0.5
  Built on 2021-11-24T08:00:00Z

Additional LLDP features:    LLDP-MED, Dot1, Dot3, Custom TLV
Additional protocols:        CDP, FDP, EDP, SONMP
SNMP support:                no
Old kernel support:          no (Linux 2.6.39+)
Privilege separation:        enabled
Privilege separation user:   lldpd
Privilege separation group:  lldpd
Privilege separation chroot: /var/run/lldpd
Configuration directory:     /etc
```

**Comment by vincentbernat** [comment]
The daemon starts in `paused` state and will specifically run `lldpcli` to unpause itself once the configuration file has been read. So, adding a `pause` statement in config will have no effect. Is there a use case for your need?

**Comment by avlec** [comment]
The indended use case was to have lldpd start on the system but not do anything until a controlling application takes over, so that if the controlling application is configured to turn off device LLDP the pause in the config covers that, and if the controlling application is configured to turn on LLDP it just runs a resume command after it has started. This is so that the init stuff can still be used but lldpd doesn't do anything until the controlling application starts.

Ultimately this is probably a niche request so I understand if this doesn't go anywhere.

**Comment by vincentbernat** [comment]
Maybe `configure lldp status disabled` would work?

**Comment by avlec** [comment]
That should work. Maybe the pause not working in the conf can be added to
the lldpcli docs?

**Comment by vincentbernat** [comment]
> That should work. Maybe the pause not working in the conf can be added to
> the lldpcli docs?

I have done that.

**Comment by avlec** [comment]
Thank you 😃
