### ISSUE TITLE
forbidden interfaces still receive lldp packets

### ISSUE THREAD

**Issue by lwintermelon** [lldpd/lldpd#556]
# Bug description
forbidden interface won't beat a simple matched interface.
## Steps to reproduce the problem

 1.  set `DAEMON_ARGS="-I *,!tap*"`

 3. restart lldpd

## Expected outcome
no lldp packets on tap* interface 

## Current outcome
There are still lldp packets on tap* interface 

# and a question here
the lldpd doc says about `-I interfaces`
>Without this option, lldpd will use all available physical interfaces.

But it seems that lldpd will use all tap device too, is this what we want？

**Comment by vincentbernat** [comment]
TAP devices are considered physical (people may want to have LLDP information on virtual hosts). There is no star after `tap` in your first comand. Can you double check?

**Comment by lwintermelon** [comment]
> TAP devices are considered physical (people may want to have LLDP information on virtual hosts). 

I see that TAP devices are econsidered physical, it's appropriate.

> There is no star after `tap` in your first comand. Can you double check?

Yes I do have a star after `tap`，so it's `DAEMON_ARGS="-I *,!tap"` in my lldpd config file, it's a typo above, have corrected it.

**Comment by vincentbernat** [comment]
Could you ensure that the pattern is the one you expect in `lldpcli show configuration`? If yes, could you run with `lldpd -dddd -D interfaces -I '*,!tap*'`. You should get a line with `deny tap0` or something like that. You should not get `tap0 is an acceptable ethernet device`. The output

**Comment by lwintermelon** [comment]
Both command you provide are very helpful. It seems that you can't add comment after line if args are with quotation marks.
So if  I have `DAEMON_ARGS="-I *,!tap*"  # comment here` in lldpd config, `lldpcli show configuration` will show `Interface pattern: *,!tap*#`.
But with `DAEMON_ARGS=-I *,!tap*  # comment here`, no quotation marks, `lldpcli show configuration` says `Interface pattern: *,!tap*`, it's ok.

The default config in `/etc/default/lldpd` is
```
# Uncomment to start SNMP subagent and enable CDP, SONMP and EDP protocol
#DAEMON_ARGS="-x -c -s -e"
```
It's trivial to uncomment the line, modifed the args,  then append a comment after the line.

**Comment by vincentbernat** [comment]
I suppose you are using systemd. It has its own expectations about this file, which may differ a bit from what a shell would expect.
