### ISSUE TITLE
Missing some MIBS for retrieving Information for Custom TLV's

### ISSUE THREAD

**Issue by pblansink** [lldpd/lldpd#567]
Hallo,

I am working on using Custom TLV's in LLDP on Linux for filling up a central Monitoring Database.
This extra Information can then be used for aggregating servers witch belong to the seam platform.

The whole Custom TLV's are working perfect thanks for that.
I only see that not all MIB's for this are implemented or I am doing something wrong ?

I am using Telegraf to get the SNMP LLDP Data into Influx and present it with Grafana.
Based on the missing MIBS the table can not being created with the right field's and the right information.

Is there a way to resolve this ?

Information:

Linux LLDPD (version 1.0.11) on Debian 11

/etc/telegraf/telegraf.d/monitor-linux-snmp.conf

[[inputs.snmp]]
  agents = [ "172.32.4.11:161"]
  version = 2
  community = "public"
  name = "snmp"

 [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.table]]
    name = "snmp"
    inherit_tags = [ "hostname" ]
    oid = "IF-MIB::ifXTable"

    [[inputs.snmp.table.field]]
      name = "ifName"
      oid = "IF-MIB::ifName"
      is_tag = true

snmpwalk -m +ALL -M +additional_mibs -c public -v2c -Ob 172.32.4.11 IF-MIB::ifName
Bad operator (INTEGER): At line 73 in /usr/share/snmp/mibs/ietf/SNMPv2-PDU
IF-MIB::ifName.1 = STRING: lo
IF-MIB::ifName.2 = STRING: eno1
IF-MIB::ifName.3 = STRING: eno2
IF-MIB::ifName.4 = STRING: eno3
IF-MIB::ifName.5 = STRING: eno4
IF-MIB::ifName.6 = STRING: vxlan10
IF-MIB::ifName.7 = STRING: vxlan20
IF-MIB::ifName.8 = STRING: vxlan40
IF-MIB::ifName.9 = STRING: vxlan90

Table Ouput is based on IF-MIB::ifName for Table IF-MIB::ifXTable

telegraf -config /etc/telegraf/telegraf.d/monitor-linux-snmp.conf --test
2023-01-02T09:25:32Z I! Starting Telegraf 1.12.1
> snmp,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a,ifName=vxlan20 ifConnectorPresent=1i,ifCounterDiscontinuityTime=0i,ifHCInBroadcastPkts=0i,ifHCInMulticastPkts=0i,ifHCInOctets=27088i,ifHCInUcastPkts=415i,ifHCOutBroadcastPkts=0i,ifHCOutMulticastPkts=0i,ifHCOutOctets=3531237i,ifHCOutUcastPkts=18376i,ifHighSpeed=1000i,ifInBroadcastPkts=0i,ifInMulticastPkts=0i,ifOutBroadcastPkts=0i,ifOutMulticastPkts=0i,ifPromiscuousMode=2i 1672651533000000000
> snmp,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a,ifName=vxlan90 ifConnectorPresent=1i,ifCounterDiscontinuityTime=0i,ifHCInBroadcastPkts=0i,ifHCInMulticastPkts=0i,ifHCInOctets=26192i,ifHCInUcastPkts=383i,ifHCOutBroadcastPkts=0i,ifHCOutMulticastPkts=0i,ifHCOutOctets=38888i,ifHCOutUcastPkts=692i,ifHighSpeed=1000i,ifInBroadcastPkts=0i,ifInMulticastPkts=0i,ifOutBroadcastPkts=0i,ifOutMulticastPkts=0i,ifPromiscuousMode=2i 1672651533000000000
> snmp,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a,ifName=eno2 ifConnectorPresent=1i,ifCounterDiscontinuityTime=0i,ifHCInBroadcastPkts=0i,ifHCInMulticastPkts=0i,ifHCInOctets=0i,ifHCInUcastPkts=0i,ifHCOutBroadcastPkts=0i,ifHCOutMulticastPkts=0i,ifHCOutOctets=0i,ifHCOutUcastPkts=0i,ifHighSpeed=0i,ifInBroadcastPkts=0i,ifInMulticastPkts=0i,ifOutBroadcastPkts=0i,ifOutMulticastPkts=0i,ifPromiscuousMode=2i 1672651533000000000
> snmp,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a,ifName=eno3 ifConnectorPresent=1i,ifCounterDiscontinuityTime=0i,ifHCInBroadcastPkts=0i,ifHCInMulticastPkts=7421i,ifHCInOctets=1279348i,ifHCInUcastPkts=26i,ifHCOutBroadcastPkts=0i,ifHCOutMulticastPkts=0i,ifHCOutOctets=891434i,ifHCOutUcastPkts=2289i,ifHighSpeed=1000i,ifInBroadcastPkts=0i,ifInMulticastPkts=7421i,ifOutBroadcastPkts=0i,ifOutMulticastPkts=0i,ifPromiscuousMode=2i 1672651533000000000
> snmp,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a,ifName=eno4 ifConnectorPresent=1i,ifCounterDiscontinuityTime=0i,ifHCInBroadcastPkts=0i,ifHCInMulticastPkts=2854731i,ifHCInOctets=288015249i,ifHCInUcastPkts=1205197i,ifHCOutBroadcastPkts=0i,ifHCOutMulticastPkts=0i,ifHCOutOctets=167091618i,ifHCOutUcastPkts=420506i,ifHighSpeed=1000i,ifInBroadcastPkts=0i,ifInMulticastPkts=2854731i,ifOutBroadcastPkts=0i,ifOutMulticastPkts=0i,ifPromiscuousMode=2i 1672651533000000000
> snmp,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a,ifName=vxlan10 ifConnectorPresent=1i,ifCounterDiscontinuityTime=0i,ifHCInBroadcastPkts=0i,ifHCInMulticastPkts=0i,ifHCInOctets=9699119i,ifHCInUcastPkts=16353i,ifHCOutBroadcastPkts=0i,ifHCOutMulticastPkts=0i,ifHCOutOctets=12846313i,ifHCOutUcastPkts=16907i,ifHighSpeed=1000i,ifInBroadcastPkts=0i,ifInMulticastPkts=0i,ifOutBroadcastPkts=0i,ifOutMulticastPkts=0i,ifPromiscuousMode=2i 1672651533000000000
> snmp,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a,ifName=eno1 ifConnectorPresent=1i,ifCounterDiscontinuityTime=0i,ifHCInBroadcastPkts=0i,ifHCInMulticastPkts=2904564i,ifHCInOctets=392514853i,ifHCInUcastPkts=1073767i,ifHCOutBroadcastPkts=0i,ifHCOutMulticastPkts=0i,ifHCOutOctets=144856933i,ifHCOutUcastPkts=650976i,ifHighSpeed=100i,ifInBroadcastPkts=0i,ifInMulticastPkts=2904564i,ifOutBroadcastPkts=0i,ifOutMulticastPkts=0i,ifPromiscuousMode=2i 1672651533000000000
> snmp,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a,ifName=vxlan40 ifConnectorPresent=1i,ifCounterDiscontinuityTime=0i,ifHCInBroadcastPkts=0i,ifHCInMulticastPkts=0i,ifHCInOctets=16795716i,ifHCInUcastPkts=237162i,ifHCOutBroadcastPkts=0i,ifHCOutMulticastPkts=0i,ifHCOutOctets=116746344i,ifHCOutUcastPkts=317308i,ifHighSpeed=1000i,ifInBroadcastPkts=0i,ifInMulticastPkts=0i,ifOutBroadcastPkts=0i,ifOutMulticastPkts=0i,ifPromiscuousMode=2i 1672651533000000000
> snmp,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a,ifName=lo ifConnectorPresent=2i,ifCounterDiscontinuityTime=0i,ifHCInBroadcastPkts=0i,ifHCInMulticastPkts=0i,ifHCInOctets=457672538i,ifHCInUcastPkts=964734i,ifHCOutBroadcastPkts=0i,ifHCOutMulticastPkts=0i,ifHCOutOctets=457672538i,ifHCOutUcastPkts=964734i,ifHighSpeed=10i,ifInBroadcastPkts=0i,ifInMulticastPkts=0i,ifOutBroadcastPkts=0i,ifOutMulticastPkts=0i,ifPromiscuousMode=2i 1672651533000000000

This is Stored correctly in the Influx Database that I am using with all Fields belonging to the IF-MIB::ifXTable MIB.

When i try to do the same for the Custom TLV's it's not working.

/etc/telegraf/telegraf.d/monitor-linux-lldp.conf

[[inputs.snmp]]
  agents = [ "172.32.4.11:161"]
  version = 2
  community = "public"
  name = "snmp"

 [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.table]]
    name = "lldpRemOrgDefInfoTable"
    inherit_tags = [ "hostname" ]
    oid = "LLDP-MIB::lldpRemOrgDefInfoTable"

    [[inputs.snmp.table.field]]
      name = "subtype"
      oid = "LLDP-MIB::lldpRemOrgDefInfoEntry"
      is_tag = true

  [[inputs.snmp.table]]
    name = "lldpRemManAddrTable"
    inherit_tags = [ "hostname" ]
    oid = "LLDP-MIB::lldpRemManAddrTable"

    [[inputs.snmp.table.field]]
      name = "lldpRemManAddrIfId"
      oid = "LLDP-MIB::lldpRemManAddrIfId"
      is_tag = true

telegraf -config /etc/telegraf/telegraf.d/monitor-linux-lldp.conf --test
2023-01-02T09:47:17Z I! Starting Telegraf 1.12.1
> lldpRemOrgDefInfoTable,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a lldpRemOrgDefInfo="178.238.96.206/32; 172.26.64.244/32" 1672652838000000000
> lldpRemOrgDefInfoTable,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a lldpRemOrgDefInfo="Mobile, 3G" 1672652838000000000
> lldpRemOrgDefInfoTable,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a lldpRemOrgDefInfo="RTP; RTP" 1672652838000000000
> lldpRemOrgDefInfoTable,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a lldpRemOrgDefInfo="RTP-Engine" 1672652838000000000
> lldpRemOrgDefInfoTable,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a lldpRemOrgDefInfo="VoiceInfra" 1672652838000000000
> lldpRemOrgDefInfoTable,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a lldpRemOrgDefInfo="SP" 1672652838000000000
> lldpRemOrgDefInfoTable,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a lldpRemOrgDefInfo="Carrier SBC (Orange)" 1672652838000000000
> lldpRemOrgDefInfoTable,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a lldpRemOrgDefInfo="dummy1; bond0.408" 1672652838000000000
> lldpRemOrgDefInfoTable,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a lldpRemOrgDefInfo="Media Proxy" 1672652838000000000
> lldpRemOrgDefInfoTable,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a lldpRemOrgDefInfo="Production" 1672652838000000000
> lldpRemOrgDefInfoTable,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a lldpRemOrgDefInfo="vw766" 1672652838000000000
> lldpRemOrgDefInfoTable,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a lldpRemOrgDefInfo="VoiceInfra" 1672652838000000000
> lldpRemManAddrTable,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a,lldpRemManAddrIfId=2 lldpRemManAddrIfSubtype=2i,lldpRemManAddrOID=".0.0" 1672652838000000000
> lldpRemManAddrTable,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a,lldpRemManAddrIfId=2 lldpRemManAddrIfSubtype=2i,lldpRemManAddrOID=".0.0" 1672652838000000000
> lldpRemManAddrTable,agent_host=172.32.4.11,host=freeswitch,hostname=kamailio-a,lldpRemManAddrIfId=61 lldpRemManAddrIfSubtype=2i,lldpRemManAddrOID=".0.0" 1672652838000000000

Table Ouput is based on LLDP-MIB::lldpRemManAddrIfId for Table LLDP-MIB::lldpRemManAddrTable

snmpwalk -m +ALL -M +additional_mibs -c public -v2c -Ob 172.32.4.11 lldpRemManAddrTable
Bad operator (INTEGER): At line 73 in /usr/share/snmp/mibs/ietf/SNMPv2-PDU
LLDP-MIB::lldpRemManAddrIfSubtype.0.2.1.1.4.0.0.0.0 = INTEGER: ifIndex(2)
LLDP-MIB::lldpRemManAddrIfSubtype.8760200.4.8.1.4.192.168.2.81 = INTEGER: ifIndex(2)
LLDP-MIB::lldpRemManAddrIfSubtype.8760200.4.8.2.16.254.128.0.0.0.0.0.0.22.88.208.255.254.90.202.160 = INTEGER: ifIndex(2)
LLDP-MIB::lldpRemManAddrIfId.0.2.1.1.4.0.0.0.0 = INTEGER: 61
LLDP-MIB::lldpRemManAddrIfId.8760200.4.8.1.4.192.168.2.81 = INTEGER: 2
LLDP-MIB::lldpRemManAddrIfId.8760200.4.8.2.16.254.128.0.0.0.0.0.0.22.88.208.255.254.90.202.160 = INTEGER: 2
LLDP-MIB::lldpRemManAddrOID.0.2.1.1.4.0.0.0.0 = OID: SNMPv2-SMI::zeroDotZero
LLDP-MIB::lldpRemManAddrOID.8760200.4.8.1.4.192.168.2.81 = OID: SNMPv2-SMI::zeroDotZero
LLDP-MIB::lldpRemManAddrOID.8760200.4.8.2.16.254.128.0.0.0.0.0.0.22.88.208.255.254.90.202.160 = OID: SNMPv2-SMI::zeroDotZero

Missing the following MIBS on LLDP-MIB::lldpRemManAddrTable for getting a Full Table View
	lldpRemManAddrSubtype
	lldpRemManAddr

Table Ouput is based on LLDP-MIB::lldpRemOrgDefInfoEntry for Table LLDP-MIB::lldpRemOrgDefInfoTable

snmpwalk -m +ALL -M +additional_mibs -c public -v2c -Ob 172.32.4.11 lldpRemOrgDefInfoTable
Bad operator (INTEGER): At line 73 in /usr/share/snmp/mibs/ietf/SNMPv2-PDU
LLDP-MIB::lldpRemOrgDefInfo.8760200.4.8.253.1.1.1.1 = STRING: "VoiceInfra"
LLDP-MIB::lldpRemOrgDefInfo.8760200.4.8.253.1.1.2.2 = STRING: "Carrier SBC (Orange)"
LLDP-MIB::lldpRemOrgDefInfo.8760200.4.8.253.1.1.3.3 = STRING: "Production"
LLDP-MIB::lldpRemOrgDefInfo.8760200.4.8.253.1.1.4.4 = STRING: "Mobile, 3G"
LLDP-MIB::lldpRemOrgDefInfo.8760200.4.8.253.1.1.5.5 = STRING: "SP"
LLDP-MIB::lldpRemOrgDefInfo.8760200.4.8.253.1.1.6.6 = STRING: "RTP-Engine"
LLDP-MIB::lldpRemOrgDefInfo.8760200.4.8.253.1.1.7.7 = STRING: "Media Proxy"
LLDP-MIB::lldpRemOrgDefInfo.8760200.4.8.253.1.1.8.8 = STRING: "vw766"
LLDP-MIB::lldpRemOrgDefInfo.8760200.4.8.253.1.1.9.9 = STRING: "dummy1; bond0.408"
LLDP-MIB::lldpRemOrgDefInfo.8760200.4.8.253.1.1.10.10 = STRING: "RTP; RTP"
LLDP-MIB::lldpRemOrgDefInfo.8760200.4.8.253.1.1.11.11 = STRING: "178.238.96.206/32; 172.26.64.244/32"
LLDP-MIB::lldpRemOrgDefInfo.8760200.4.8.253.1.2.1.12 = STRING: "VoiceInfra"

Missing the following MIBS on LLDP-MIB::lldpRemOrgDefInfoTable for getting a Full Table View
	lldpRemOrgDefInfoOUI 
	lldpRemOrgDefInfoSubtype
	lldpRemOrgDefInfoIndex

By missing the lldpRemOrgDefInfoSubtype or lldpRemOrgDefInfoIndex Telegraf Application will not create a table based on a index so we have a unique line per entry.

At this moment we will see only one Entry per time, Entry's are overwrition becaise there is no unique index field.

Influx:

1672653270000000000 172.32.4.11 freeswitch kamailio-a VoiceInfra
1672653280000000000 172.32.4.11 freeswitch kamailio-a RTP; RTP
1672653290000000000 172.32.4.11 freeswitch kamailio-a Production
1672653300000000000 172.32.4.11 freeswitch kamailio-a RTP-Engine
1672653310000000000 172.32.4.11 freeswitch kamailio-a VoiceInfra
1672653320000000000 172.32.4.11 freeswitch kamailio-a VoiceInfra
1672653330000000000 172.32.4.11 freeswitch kamailio-a Media Proxy
1672653340000000000 172.32.4.11 freeswitch kamailio-a SP
1672653350000000000 172.32.4.11 freeswitch kamailio-a 178.238.96.206/32; 172.26.64.244/32
1672653360000000000 172.32.4.11 freeswitch kamailio-a SP

[lldpcli] # sh neighbors

Interface:    eno3, via: LLDP, RID: 8, Time: 0 day, 01:01:59
  Chassis:
    ChassisID:    mac 14:58:d0:5a:ca:a0
    SysName:      freeswitch.home
    SysDescr:     Debian GNU/Linux 11 (bullseye) Linux 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64
    MgmtIP:       192.168.2.81
    MgmtIface:    2
    MgmtIP:       fe80::1658:d0ff:fe5a:caa0
    MgmtIface:    2
    Capability:   Bridge, off
    Capability:   Router, off
    Capability:   Wlan, off
    Capability:   Station, on
  Port:
    PortID:       mac 14:58:d0:5a:ca:a2
    PortDescr:    eno3
    TTL:          120
  Unknown TLVs:
    TLV:          OUI: FD,01,01, SubType: 1, Len: 10 56,6F,69,63,65,49,6E,66,72,61
    TLV:          OUI: FD,01,01, SubType: 2, Len: 20 43,61,72,72,69,65,72,20,53,42,43,20,28,4F,72,61,6E,67,65,29
    TLV:          OUI: FD,01,01, SubType: 3, Len: 10 50,72,6F,64,75,63,74,69,6F,6E
    TLV:          OUI: FD,01,01, SubType: 4, Len: 10 4D,6F,62,69,6C,65,2C,20,33,47
    TLV:          OUI: FD,01,01, SubType: 5, Len: 2 53,50
    TLV:          OUI: FD,01,01, SubType: 6, Len: 10 52,54,50,2D,45,6E,67,69,6E,65
    TLV:          OUI: FD,01,01, SubType: 7, Len: 11 4D,65,64,69,61,20,50,72,6F,78,79
    TLV:          OUI: FD,01,01, SubType: 8, Len: 5 76,77,37,36,36
    TLV:          OUI: FD,01,01, SubType: 9, Len: 17 64,75,6D,6D,79,31,3B,20,62,6F,6E,64,30,2E,34,30,38
    TLV:          OUI: FD,01,01, SubType: 10, Len: 8 52,54,50,3B,20,52,54,50
    TLV:          OUI: FD,01,01, SubType: 11, Len: 35 31,37,38,2E,32,33,38,2E,39,36,2E,32,30,36,2F,33,32,3B,20,31,37,32,2E,32,36,2E,36,34,2E,32,34,34,2F,33,32
    TLV:          OUI: FD,01,02, SubType: 1, Len: 10 56,6F,69,63,65,49,6E,66,72,61
-------------------------------------------------------------------------------

**Comment by vincentbernat** [comment]
On 2023-01-02 11:15, pblansink wrote:

> Missing the following MIBS on LLDP-MIB::lldpRemManAddrTable for getting 
> a Full Table View
> lldpRemManAddrSubtype
> lldpRemManAddr

They are "MAX-ACCESS" "not-accessible".

> Missing the following MIBS on LLDP-MIB::lldpRemOrgDefInfoTable for 
> getting a Full Table View
> lldpRemOrgDefInfoOUI
> lldpRemOrgDefInfoSubtype
> lldpRemOrgDefInfoIndex

Same here.

This is usually the case for everything that is used as an index.
