### ISSUE TITLE
lldpctl accepts commands from lldpcli

### ISSUE THREAD

**Issue by kiltum** [lldpd/lldpd#573]
When using auto-completion wtih TAB, very easy mix lldpctl and lldpcli

example

```
# lldpctl show ne
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
#
```
Oops, we lost routers, lets go to network people and ask them to  fix ... but wait ;)
```
# lldpcli show ne
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
Interface:    enp175s0f1np1, via: LLDP, RID: 1, Time: 0 day, 00:19:20
  Chassis:     
    ChassisID:    mac a4:be:2b:ba:fa:a1
    SysName:      exter-ulf-003
    SysDescr:     Huawei Versatile Routing Platform Software
...
```

uf-f, all ok, we just call wrong command (pass that I know, that lldpctl is symlink to lldpcli, but why so such difference in output?)

Ubuntu 22.04.01

```
#  lldpcli -vv
lldpcli 1.0.13
  Built on 2021-11-13T15:11:47Z

Additional output formats:   TEXT, KV, JSON, XML

C compiler command: C compiler command is not available for reproducible builds
Linker command:     Linker compiler command is not available for reproducible builds
```

# Bug description

## Steps to reproduce the problem

1. install and run lldpd as you wish
2. call lldpctl with same arguments that you use with lldpcli (see above)

## Expected outcome

Error message like  "no such command" or something like this

## Current outcome

Normal output, but without results

**Comment by vincentbernat** [comment]
`lldpctl` accepts interfaces as arguments to restrict the output. That's why the `lldpcli` command was introduced as a separate command. I don't see what we could do that wouldn't break someone else workflow.
