### ISSUE TITLE
Memory leak in `kv_data` function

### ISSUE THREAD

**Issue by hovhannes-96** [lldpd/lldpd#599]
The memory leak is found by a static analyzer developed at CAST ( https://www.linkedin.com/company/cast-center/).

In src/client/kv_writer.c call of [strdup](https://github.com/lldpd/lldpd/blob/c6eebc0686790d4072687ffb01cea19323e1df2a/src/client/kv_writer.c#L55C12-L55C12) allocates and returns dynamic memory which is not freed if the [key](https://github.com/lldpd/lldpd/blob/c6eebc0686790d4072687ffb01cea19323e1df2a/src/client/kv_writer.c#L57C9-L57C9) is a NULL pointer.

**Comment by vincentbernat** [comment]
`fatal()` terminates the program. No need to free memory in this case.
