### ISSUE TITLE
In some cases lldpd cannot get all interfaces

### ISSUE THREAD

**Issue by qyp0203** [lldpd/lldpd#611]
```
# lldpcli -vv
admin@sutc-a02-40u-bizleaf0101:~$ lldpcli -v
1.0.5
```

# Bug description
Create many interfaces on the device, including vlan, lag, eth, and vxlan. The number exceeds a thousand. Start lldpd repeatedly and execute lldpcli show interface detail. Sometimes only some of the created interfaces are displayed.

**Comment by qyp0203** [comment]
I looked at the code. It should be that during initialization, when receiving the GETLINK message, the receiving process was interrupted by a notification from the kernel.
![image](https://github.com/lldpd/lldpd/assets/107174759/a59ff89d-e1e7-4e49-ae9d-d62177ef9146)

Receiving a message without the NLM_F_MULTI flag causes recv to exit.

**Comment by vincentbernat** [comment]
The code you show is not the one you are running. There is some additional code to handle `recvmsg()` being interrupted. Do you get `should have received something, but didn't` in your logs?
