### ISSUE TITLE
No error message upon requesting non-existing interface.

### ISSUE THREAD

**Issue by hboetes** [lldpd/lldpd#620]
Whilst using `lldpctl` the wrong way:

```
%  sudo lldpctl neighbors
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
```
…a slip of the mind, using the syntax which should be used on a Cisco switch — no error returned; just empty output.

Wouldn't it be nice if `lldpctl` would return an error, like `no such ethernet device: neighbors`.

```
%  sudo lldpcli -vv
lldpcli 1.0.16
  Built on 2023-09-21T21:34:19Z

Additional output formats:   TEXT, KV, JSON, XML

C compiler command: C compiler command is not available for reproducible builds
Linker command:     Linker compiler command is not available for reproducible builds

```

**Comment by vincentbernat** [comment]
With the way this is done, this is not possible. lldpctl does not makes the difference between an interface that does not exist or has no neighbor. Also, lldpctl does not contain platform-specific code to check that.
