### ISSUE TITLE
Update RPM bundle for EPEL or AlmaLinux 8/9 Support

### ISSUE THREAD

**Issue by kitos9112** [lldpd/lldpd#654]
Just realised there's no recent RPM build support for Almalinux 8/9 (e.g. via EPEL) beyond `1.0.4` from Appstream that includes recent upstream releases.

Are there any plans to get these added? Or made them available via [vbernat third party repo](https://download.opensuse.org/repositories/home:/vbernat/)

Thanks!

**Comment by boomertsfx** [comment]
EPEL is EPEL -- `lldpd` installs fine on any `el{7,8,9}` for me

**Comment by kitos9112** [comment]
Yes, it's indeed in the appstream repo but it uses a pretty old version (1.0.4) which is not even available in this upstream releases.

I should have clarified that I meant a non-official RPM source but the one @vincentbernat maintains in Opensuse (https://download.opensuse.org/repositories/home:/vbernat/)

**Comment by boomertsfx** [comment]
oh wow, didn't even notice that (the old version) -- we're still mostly el7 and it's in EPEL there, so I'm not if that complicates things since the EPEL version would be overriding the "official" version?

**Comment by kitos9112** [comment]
Ye, we'd not have noticed either until our lldp monitoring alerts began reporting the Mac address instead of the server interface name.

I guess the rpm package hasn't changed much. I may look into pack it up myself, but just touching base in case the upstream would get it done.

**Comment by vincentbernat** [comment]
> Yes, it's indeed in the appstream repo but it uses a pretty old version (1.0.4) which is not even available in this upstream releases.
> 
> I should have clarified that I meant a non-official RPM source but the one @vincentbernat maintains in Opensuse (https://download.opensuse.org/repositories/home:/vbernat/)

The one here are not the one in EPEL. In OSC, I cannot build for AlmaLinux.

**Comment by vincentbernat** [comment]
Not a thing that I can fix "upstream".

**Comment by boomertsfx** [comment]
you should only have to compile for RHEL9 -- just like EPEL -- EPEL is compatible with all the EL variants 🤷‍♂️

**Comment by kitos9112** [comment]
Ye, I'll build it for RHEL9 myself

**Comment by boomertsfx** [comment]
> Ye, I'll build it for RHEL9 myself

Are you going to use the SRPM from EPEL7 and just go from there?  I'd like to do something similar until someone has a modern lldpd in popular EL8/9 repos

**Comment by kitos9112** [comment]
> > Ye, I'll build it for RHEL9 myself
> 
> Are you going to use the SRPM from EPEL7 and just go from there? I'd like to do something similar until someone has a modern lldpd in popular EL8/9 repos

Haven't thoughtfully thought about it. I may end up using a public-facing Github repo that builds and publishes AL8/9 or EL8/9 RPMs using rpm-build and mock tools.

Something in these lines.

https://github.com/mmornati/docker-mock-rpmbuilder
