### ISSUE TITLE
unable to connect to socket /usr/local/var/run/lldpd.socket: No such file or directory

### ISSUE THREAD

**Issue by bogireddy-reddy** [lldpd/lldpd#668]
This is an example of bug report. Read it to the bottom and Try to
adapt it to your case. Please, do not use this template for
configuration problems, getting help on how to compile, cross-compile
on some platforms. Keep in mind that *lldpd* has been deployed
successfully on hundred of thousands of devices and therefore it is
unlikely it just does not work. Instead, use the
[discussions](https://github.com/lldpd/lldpd/discussions) for support
questions.

When putting code snippets (logs, commands), put them between triple
backticks:

```
# lldpcli -vv
lldpcli 2024-04-01
  Built on 2024-04-01T10:53:25Z

Additional output formats:   TEXT, KV, JSON

C compiler command: gcc  -fdiagnostics-show-option -fdiagnostics-color=auto -fno-omit-frame-pointer -funsigned-char -pipe -Wall -W -Wextra -Wformat -Wformat-security -Wimplicit-fallthrough -Wfatal-errors -Winline -Wpointer-arith -Wmissing-prototypes -Wno-cast-align -Wno-unused-parameter -Wno-missing-field-initializers -Wno-sign-compare -fstack-protector -fstack-protector-all -fstack-protector-strong -fstack-clash-protection  -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -g -O2 
Linker command:     /usr/bin/ld -m elf_x86_64  -Wl,-z,relro -Wl,-z,now 

# Bug description

## Steps to reproduce the problem

 1. Compile `lldpd` with `./configure --localstatedir=/var --with-snmp && make`.
 2. 
configure: error: in `/home/bnreddy/Desktop/lldpd-master-1.0.0/lldpd-master':
configure: error: *** no NetSNMP support found
See `config.log' for more details

 3. Install with `sudo make install`.

 4. Run `lldpd`.

 5. Wait for a LLDPDU from the remote switch (vendor Pisco, release 19.1(478)KHT47.3).

## Expected outcome

`lldpd` should accept the LLDPDU and it should be available in the
output of `lldpcli show neighbors details`.

lldpcli show neighbors details
2024-06-20T15:05:15 [WARN/control] unable to connect to socket /usr/local/var/run/lldpd.socket: No such file or directory

After executing the above steps, `lldpd` crashed. Here is the end of
the output of `lldpd -ddddd` before the crash:

```
2016-11-10T11:06:40 [ DBG/lldp] receive LLDP PDU on eno1
2016-11-10T11:06:40 [ DBG/alloc] allocate a new management address (family: 1)
2016-11-10T11:06:40 [ DBG/decode] search for the same MSAP
2016-11-10T11:06:40 [ DBG/decode] MSAP is unknown, search for the chassis
2016-11-10T11:06:40 [ DBG/decode] unknown chassis, add it to the list
```

# Additional information

 - Output of `lldpd -vv`:

```
lldpd x.y.z
  Built on ...

Additional LLDP features: ...
Additional protocols: ...
```

 - Output of `ps -fp $(pgrep -d, -x lldpd)`:

```
UID        PID  PPID  C STIME TTY          TIME CMD
root      2265     1  0 nov.05 ?       00:00:00 lldpd: monitor.
_lldpd    2285  2265  0 nov.05 ?       00:00:00 lldpd: connected to gs108t.
```

 - Output of `uname -sro`:

```
Linux 4.8.0-1-amd64 GNU/Linux
```

 - Output of `tcpdump -pni eth0 -vv -X ether host 01:80:c2:00:00:0e`:

```
16:47:37.595387 LLDP, length 219
        Chassis ID TLV (1), length 7
          Subtype MAC address (4): 54:ee:75:0f:31:7e
          0x0000:  0454 ee75 0f31 7e
[...]
        0x00b0:  1600 080f 656e 7830 3035 3062 3636 6563  ....enx0050b66ec
        0x00c0:  6236 65fe 0900 120f 0301 0000 0000 fe09  b6e.............
        0x00d0:  0012 0f01 03ec c100 1e00 00              ...........
```

**Comment by vincentbernat** [comment]
No actionable information in this bug report.

**Comment by bogireddy-reddy** [comment]
Hi @vincentbernat,
             This issue has been resolved and it is working fine on my PC. The details are given below:

lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 20.04.6 LTS
Release: 20.04
Codename: focal

However, I need to integrate this into my project, but the devices used in my project have not been working. When I run the `lldpcli` command, it has not created a prompt. My Linux board details are mentioned below:

My system has been using BusyBox, which is a lightweight set of Unix utilities combined into a single small executable.

BusyBox v1.20.2 (2024-06-20 11:32:26 IST) multi-call binary.

cat /etc/os-release
NAME=Buildroot
VERSION=2012.11-gcc6652c-dirty
ID=buildroot
VERSION_ID=2012.11
PRETTY_NAME="Buildroot 2012.11"

uname -a
Linux 8PortOLT 3.6.5-Broadcom Linux #2 SMP Thu Jun 20 12:24:21 IST 2024 armv7l GNU/Linux
 


Please help me to sort this out.
