### ISSUE TITLE
Obtained the neighbor information of multiple network ports from one NIC port?

### ISSUE THREAD

**Issue by ouyangxx10** [lldpd/lldpd#669]
Migrating lldpd to the BMC system to obtain information about neighboring switches.
There is a network card on the system, and there are 2 network ports on the network card, and the network cables are connected to the two network ports, and the IP is automatically assigned.

Only one network port shares the network to the BMC, and the BMC uses lldpcli to obtain information about adjacent devices (switches).
The switch information of the two network ports on the NIC is obtained through this shared network port.

Why is the switch information of the entire NIC obtained through a network port? Or is it a problem with the lldpd tool? or netadapter?

```
root@testp4:~# lldpcli -v
1.0.17
root@testp4:~#
```

![lldp-info](https://github.com/lldpd/lldpd/assets/26786288/012594ed-ac5d-4a84-8677-ae9bd9a7081a)

**Comment by vincentbernat** [comment]
You can check with tcpdump that both LLDP packets are received on eth1 (see the README or the bug template you removed). lldpd can't know which one is correct and is displaying both.
