### ISSUE TITLE
Can't restrict which interface the MgmtIP is picked from

### ISSUE THREAD

**Issue by wilhelmy** [lldpd/lldpd#682]
```
# lldpcli -vv
lldpcli 1.0.4
  Built on 2019-06-15T09:14:45Z

Additional output formats:   TEXT, KV, JSON

C compiler command: aarch64-guf-linux-gcc  -mcpu=cortex-a53+crc+crypto -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/app/build-imx8mguf/tmp/work/aarch64-guf-linux/lldpd/1.0.4-r0/recipe-sysroot  -fdiagnostics-show-option -fdiagnostics-color=auto -pipe -Wall -W -Wextra -Wformat -Wformat-security -Wimplicit-fallthrough -Wfatal-errors -Wcast-align -Winline -Wpointer-arith -fno-omit-frame-pointer -Wno-unused-parameter -Wno-missing-field-initializers -Wno-sign-compare -fstack-protector -fstack-protector-all -fstack-protector-strong -fstack-clash-protection -DLIBBSD_OVERLAY -isystem /app/build-imx8mguf/tmp/work/aarch64-guf-linux/lldpd/1.0.4-r0/recipe-sysroot/usr/include/bsd  -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/app/build-imx8mguf/tmp/work/aarch64-guf-linux/lldpd/1.0.4-r0=/usr/src/debug/lldpd/1.0.4-r0                      -fdebug-prefix-map=/app/build-imx8mguf/tmp/work/aarch64-guf-linux/lldpd/1.0.4-r0=/usr/src/debug/lldpd/1.0.4-r0                      -fdebug-prefix-map=/app/build-imx8mguf/tmp/work/aarch64-guf-linux/lldpd/1.0.4-r0/recipe-sysroot=                      -fdebug-prefix-map=/app/build-imx8mguf/tmp/work/aarch64-guf-linux/lldpd/1.0.4-r0/recipe-sysroot-native=  -DLIBBSD_OVERLAY -isystem /app/build-imx8mguf/tmp/work/aarch64-guf-linux/lldpd/1.0.4-r0/recipe-sysroot/usr/include/bsd 
Linker command:     aarch64-guf-linux-ld --sysroot=/app/build-imx8mguf/tmp/work/aarch64-guf-linux/lldpd/1.0.4-r0/recipe-sysroot   -Wl,-z,relro -Wl,-z,now -lbsd  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now  -lbsd
```

# Bug description

When there's more than one interface (in our case en0, en1 - both bridged together as br0 and usb0), lldpd will pick an IP address matching the mask specified in `-m` from any interface, even the ones it does not listen on. This includes for example the usb0 interface that's none of its business. The fe80::/8 IPv6LL address is automatically assigned on all active interfaces, however it is random. We want to be able to tell lldpd to use the IP from br0 as its MgmtIP.

## Steps to reproduce the problem

We run lldpd with the following arguments: 
`DAEMON_ARGS="-C en0 -I en\* -m fe80:\*"`

## Expected outcome

Being able to specify which interface to pick the MgmtIP from

## Proposed solution

`lldpd` should add a command line flag to restrict which interfaces it picks its MgmtIP value from. Alternatively, `-C` or `-I` should be honored when picking a MmgtIP from an interface.

**Comment by vincentbernat** [comment]
`-m` accepts interface names as well. So `-m br0`.

**Comment by wilhelmy** [comment]
This is not mentioned in the manpage.

**Comment by vincentbernat** [comment]
Your version may be too old. I don't remember when it was added.

**Comment by vincentbernat** [comment]
It  says:
> If  an  interface name is matched, the first IPv4 address and the first IPv6 address associated to this interface will be chosen.

**Comment by wilhelmy** [comment]
My mistake, I didn't understand that sentence (how can an interface be matched if this is never mentioned in the text block before? what's the meaning of "matching an interface"?). So it's certainly there, I'm now not sure if it makes sense to clarify it, or perhaps say "if an interface name is passed instead" or "provided".

Contrary to what I said earlier It doesn't work for our use case - we specifically need the link local address and no IPv4 address ever, but from that particular interface, and we can't specify it as a negative `fe80:*,!usb0`. We'll probably use some `ip -br addr show dev br0 | tr ' ' '\n' | grep -Eo 'fe80:[0-9a-f:]+'` way to pass an explicit address via the commandline instead because I don't want to take up more of your time, but I also can't make enough time to get acquainted with the lldpd codebase to the point that can be of any help.

Thank you for lldpd, I like it.

**Comment by wilhelmy** [comment]
If no one asks the same question again, it probably does not need to be clarified.
