### ISSUE TITLE
lldpd floods kernel log due ethtool use

### ISSUE THREAD

**Issue by joakim-tjernlund** [lldpd/lldpd#685]
USB eth interfaces often need firmware to function and drivers prints a msg when FW is loaded:
```
[    5.662415] r8152 4-3.1:1.0 eth1: v1.12.13
```
When no eth cable is connected, device is sleeping and needs to load FW when woken up.
```ethtool -S eth1``` on such interfaces wakes eth interface up again and that causes a new log msg.

lldpd  polls all I/Fs regularly so kernel log fills up.
Could lldpd check if eth I/F is RUNNING before performing ethtool on interface?

**Comment by vincentbernat** [comment]
I have fixed that in e99f4e1. Are `ethtool -i` and `ethtool -P` also a problem?

**Comment by joakim-tjernlund** [comment]
> I have fixed that in [e99f4e1](https://github.com/lldpd/lldpd/commit/e99f4e1ef4b75201e9827822546466ec8e607cfa). Are `ethtool -i` and `ethtool -P` also a problem?

I will check next week when back at work, Thanks!

**Comment by joakim-tjernlund** [comment]
> > I have fixed that in [e99f4e1](https://github.com/lldpd/lldpd/commit/e99f4e1ef4b75201e9827822546466ec8e607cfa). Are `ethtool -i` and `ethtool -P` also a problem?
> 
> I will check next week when back at work, Thanks!

ethtool -i has the same problem.
ethtool -P does NOT have the problem

Thanks

**Comment by joakim-tjernlund** [comment]
Output from ethtool -i eth1
driver: r8152
version: v1.12.13
firmware-version: rtl8153b-2 v2 04/27/23
expansion-rom-version: 
bus-info: usb-0000:00:0d.0-3.1
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no

**Comment by vincentbernat** [comment]
It's more difficult than I would expect. I need `ethtool -i` to know if the driver is allowed or not. The problem to not do that when the interface is down, is that I don't have the same interface list as when the interface is up. I need to keep interface down because they may have configuration attached to them that should be restored when the interface comes back up.

Looking at the source code of r8152 driver, I don't quite understand when it would wake up the device to get driver info. Which kernel are you running?

**Comment by joakim-tjernlund** [comment]
> 
> Looking at the source code of r8152 driver, I don't quite understand when it would wake up the device to get driver info. Which kernel are you running?

6.6.58 on Gentoo

**Comment by joakim-tjernlund** [comment]
Odd, I see this now(triggering FW reload too):
```
[], 32, 17738)            = 0
write(13, "\1\200\302\0\0\16t]\"\272v4\210\314\2\7\4\262\314\242\33_\362\4\7\3t]\"\272v4"..., 232) = 232
epoll_wait(7, [{events=EPOLLIN, data={u32=10, u64=10}}], 32, 30000) = 1
recvmsg(10, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000100}, msg_namelen=12, msg_iov=[{iov_base=[{nlmsg_len=72, nlmsg_type=RTM_NEWADDR, nlmsg_flags=0, nlmsg_seq=0, nlmsg_pid=0}, {ifa_family=AF_INET6, ifa_prefixlen=64, ifa_flags=0, ifa_scope=RT_SCOPE_UNIVERSE, ifa_index=if_nametoindex("eth0")}, [[{nla_len=20, nla_type=IFA_ADDRESS}, inet_pton(AF_INET6, "2a02:1420:1:72:765d:22ff:feba:7634")], [{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=604800, ifa_valid=2592000, cstamp=1273, tstamp=8930386}], [{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_NOPREFIXROUTE]]], iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_PEEK|MSG_TRUNC) = 72
recvmsg(10, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000100}, msg_namelen=12, msg_iov=[{iov_base=[{nlmsg_len=72, nlmsg_type=RTM_NEWADDR, nlmsg_flags=0, nlmsg_seq=0, nlmsg_pid=0}, {ifa_family=AF_INET6, ifa_prefixlen=64, ifa_flags=0, ifa_scope=RT_SCOPE_UNIVERSE, ifa_index=if_nametoindex("eth0")}, [[{nla_len=20, nla_type=IFA_ADDRESS}, inet_pton(AF_INET6, "2a02:1420:1:72:765d:22ff:feba:7634")], [{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=604800, ifa_valid=2592000, cstamp=1273, tstamp=8930386}], [{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_NOPREFIXROUTE]]], iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 72
epoll_wait(7, [{events=EPOLLIN, data={u32=10, u64=10}}], 32, 1000) = 1
recvmsg(10, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000100}, msg_namelen=12, msg_iov=[{iov_base=[{nlmsg_len=72, nlmsg_type=RTM_NEWADDR, nlmsg_flags=0, nlmsg_seq=0, nlmsg_pid=0}, {ifa_family=AF_INET6, ifa_prefixlen=64, ifa_flags=0, ifa_scope=RT_SCOPE_UNIVERSE, ifa_index=if_nametoindex("eth0")}, [[{nla_len=20, nla_type=IFA_ADDRESS}, inet_pton(AF_INET6, "2a02:1420:1:72:765d:22ff:feba:7634")], [{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=604800, ifa_valid=2592000, cstamp=1273, tstamp=8930386}], [{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_NOPREFIXROUTE]]], iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_PEEK|MSG_TRUNC) = 72
recvmsg(10, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000100}, msg_namelen=12, msg_iov=[{iov_base=[{nlmsg_len=72, nlmsg_type=RTM_NEWADDR, nlmsg_flags=0, nlmsg_seq=0, nlmsg_pid=0}, {ifa_family=AF_INET6, ifa_prefixlen=64, ifa_flags=0, ifa_scope=RT_SCOPE_UNIVERSE, ifa_index=if_nametoindex("eth0")}, [[{nla_len=20, nla_type=IFA_ADDRESS}, inet_pton(AF_INET6, "2a02:1420:1:72:765d:22ff:feba:7634")], [{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=604800, ifa_valid=2592000, cstamp=1273, tstamp=8930386}], [{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_NOPREFIXROUTE]]], iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 72
epoll_wait(7, [], 32, 1000)             = 0
ioctl(6, SIOCGIWNAME, 0x7ffd3bdbf760)   = -1 EOPNOTSUPP (Operation not supported)
ioctl(6, SIOCGIWNAME, 0x7ffd3bdbf760)   = -1 EOPNOTSUPP (Operation not supported)
ioctl(6, SIOCGIWNAME, 0x7ffd3bdbf760)   = 0
ioctl(6, SIOCGIWNAME, 0x7ffd3bdbf760)   = -1 EOPNOTSUPP (Operation not supported)
ioctl(6, SIOCGIWNAME, 0x7ffd3bdbf760)   = -1 EOPNOTSUPP (Operation not supported)
ioctl(6, SIOCGIWNAME, 0x7ffd3bdbf760)   = -1 EOPNOTSUPP (Operation not supported)
ioctl(6, SIOCETHTOOL, 0x7ffd3bdbe9b0)   = -1 EOPNOTSUPP (Operation not supported)
ioctl(6, SIOCETHTOOL, 0x7ffd3bdbe9b0)   = 0
ioctl(6, SIOCETHTOOL, 0x7ffd3bdbe9b0)   = -1 EOPNOTSUPP (Operation not supported)
ioctl(6, SIOCETHTOOL, 0x7ffd3bdbe9b0)   = 0
```
No mention of eth1 in there, eth0 is my normal e1000 LAN connection.

**Comment by joakim-tjernlund** [comment]
Ahh, it is probably inside the one of the:
```
ioctl(6, SIOCETHTOOL, 0x7ffd3bdbe9b0) ...
```

**Comment by vincentbernat** [comment]
You mean you compiled lldpd from git and there is still a wakeup?

I have looked at 6.6.58 and there is nothing that should wakeup when using `ethtool -i`:

```c
static void rtl8152_get_drvinfo(struct net_device *netdev,
				struct ethtool_drvinfo *info)
{
	struct r8152 *tp = netdev_priv(netdev);

	strscpy(info->driver, MODULENAME, sizeof(info->driver));
	strscpy(info->version, DRIVER_VERSION, sizeof(info->version));
	usb_make_path(tp->udev, info->bus_info, sizeof(info->bus_info));
	if (!IS_ERR_OR_NULL(tp->rtl_fw.fw))
		strscpy(info->fw_version, tp->rtl_fw.version,
			sizeof(info->fw_version));
}
```

This is different of `ethtool -S` which queries the device.

However, I see that for all drivers, there is this code at the end of `ethtool_get_drvinfo`:

```c
	if (!rsp->info.fw_version[0])
		rsp->devlink = netdev_to_devlink_get(dev);
```

This was introduced in ddb6e99e2db14d4b3c22a0dbddc6a09234856bb7 as an alternative to get the firmware version when drvinfo does not provide it (even on purpose) and I suppose that's this piece of code that wakes up the device.

We could use sysfs instead, but that's a pita.

**Comment by joakim-tjernlund** [comment]
> You mean you compiled lldpd from git and there is still a wakeup?

No, I just reran 1.0.18, silly me.
But now I build git and it looks fine, there is just one:
  r8152 2-3.1:1.0: load rtl8153b-2 v2 04/27/23 successfully
msg which happens when lldpd starts. I can live with that :)
> 
> I have looked at 6.6.58 and there is nothing that should wakeup when using `ethtool -i`:
> 
> ```c
> static void rtl8152_get_drvinfo(struct net_device *netdev,
> 				struct ethtool_drvinfo *info)
> {
> 	struct r8152 *tp = netdev_priv(netdev);
> 
> 	strscpy(info->driver, MODULENAME, sizeof(info->driver));
> 	strscpy(info->version, DRIVER_VERSION, sizeof(info->version));
> 	usb_make_path(tp->udev, info->bus_info, sizeof(info->bus_info));
> 	if (!IS_ERR_OR_NULL(tp->rtl_fw.fw))
> 		strscpy(info->fw_version, tp->rtl_fw.version,
> 			sizeof(info->fw_version));
> }
> ```
> 
> This is different of `ethtool -S` which queries the device.
> 
> However, I see that for all drivers, there is this code at the end of `ethtool_get_drvinfo`:
> 
> ```c
> 	if (!rsp->info.fw_version[0])
> 		rsp->devlink = netdev_to_devlink_get(dev);
> ```
> 
> This was introduced in ddb6e99e2db14d4b3c22a0dbddc6a09234856bb7 as an alternative to get the firmware version when drvinfo does not provide it (even on purpose) and I suppose that's this piece of code that wakes up the device.

OK, then this last case is a kernel issue I guess ?
> 
> We could use sysfs instead, but that's a pita.

**Comment by vincentbernat** [comment]
OK, so on first ethtool -i, the firmware is loaded and its version is kept in memory, so the second part of the code is not triggered a second time.

I suppose we can close this issue then.

**Comment by joakim-tjernlund** [comment]
> OK, so on first ethtool -i, the firmware is loaded and its version is kept in memory, so the second part of the code is not triggered a second time.
> 
> I suppose we can close this issue then.

Don't think so, I think lldpd only ask fro ethtool -i on startup.
My memory is that each ethtool -i triggers a print out.

**Comment by joakim-tjernlund** [comment]
Release soon?
