### ISSUE TITLE
Build system not finding readline-like library

### ISSUE THREAD

**Issue by rbu9fe** [lldpd/lldpd#686]
We're building lldpd using Conan as a package manager and define the appropriate dependencies to e.g. libcap or libeditline, which are installed somehwere into the Conan cache. The lldpd build toolchain is able to find e.g. libcap, however, it doesn't find libeditline. I assume it's because for other dependencies `PKGCONF` is used (which detects the installed libraries using pc files that Conan provides), whereas the readline-like libraries are expected at well-known locations only. Hence, with the current build system we're unable to build with readline support. 

Can you please check whether it's possible to fix that in the build system?

**Comment by vincentbernat** [comment]
Does libeditline comes with a .pc file?

**Comment by rbu9fe** [comment]
Yes

**Comment by rbu9fe** [comment]
Thanks for adding pkg-config support for readline. However, there is a small type which can be fixed with [this PR](https://github.com/lldpd/lldpd/pull/691).
